### ISSUE TITLE
Many UnicodeDecodeError in Kibana

### ISSUE THREAD

**Issue by magopian** [mozilla/addons-server#1090]
Seems they are all coming from the theme update checks:
```
Type: <type 'exceptions.UnicodeDecodeError'>, 'utf8' codec can't decode byte 0xe4 in position 43: invalid continuation byte. Data: :./services/utils.py:143#012Traceback (most recent call last):#012 File "./services/theme_update.py", line 219, in application#012 output = update.get_json()#012 File "./services/theme_update.py", line 160, in get_json#012 return json.dumps(data)#012 File "/usr/lib64/python2.7/json/__init__.py", line 243, in dumps#012 return _default_encoder.encode(obj)#012 File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode#012 chunks = self.iterencode(o, _one_shot=True)#012 File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode#012 return _iterencode(o, 0)#012UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 43: invalid continuation byte
```

In kibana (no clue how to link to a specific log line):
- Timestamp: 2015-12-16T09:27:49.000Z
- Uuid: 12ca5d78-3c52-4a0a-a54c-a6596a21b39b
- id_: AVGqHgsWe0LBY8qQvheY

**Comment by andymckay** [comment]
As noted in the chat with @jasonthomas this got reverted.
