### ISSUE TITLE
django-babel doesn't seem to be Django 2.2 comptible

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11233]
Running the l10n extraction I received the following traceback:

```
  src/olympia/lib/akismet/templates/admin/akismet/akismetreport/change_form.html
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/chris/.virtualenvs/olympia/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/chris/.virtualenvs/olympia/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/chris/.virtualenvs/olympia/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/chris/.virtualenvs/olympia/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/chris/.virtualenvs/olympia/lib/python3.7/site-packages/puente/management/commands/extract.py", line 39, in handle
    msgid_bugs_address=get_setting('MSGID_BUGS_ADDRESS'),
  File "/home/chris/.virtualenvs/olympia/lib/python3.7/site-packages/puente/commands.py", line 122, in extract_command
    for filename, lineno, msg, cmts, ctxt in extracted:
  File "/home/chris/.virtualenvs/olympia/lib/python3.7/site-packages/babel/messages/extract.py", line 157, in extract_from_dir
    dirpath=absname,
  File "/home/chris/.virtualenvs/olympia/lib/python3.7/site-packages/babel/messages/extract.py", line 212, in check_and_call_extract_file
    strip_comment_tags=strip_comment_tags
  File "/home/chris/.virtualenvs/olympia/lib/python3.7/site-packages/babel/messages/extract.py", line 241, in extract_from_file
    strip_comment_tags))
  File "/home/chris/.virtualenvs/olympia/lib/python3.7/site-packages/babel/messages/extract.py", line 294, in extract
    func = getattr(__import__(module, {}, {}, [attrname]), attrname)
  File "/home/chris/.virtualenvs/olympia/lib/python3.7/site-packages/django_babel/extract.py", line 2, in <module>
    from django.template.base import Lexer, TOKEN_TEXT, TOKEN_VAR, TOKEN_BLOCK
ImportError: cannot import name 'TOKEN_TEXT' from 'django.template.base' (/home/chris/.virtualenvs/olympia/lib/python3.7/site-packages/django/template/base.py)
```

I haven't looked at this more in detail but I'll check upstream (I've been maintainer here some years ago) or check if we need to do some other changes.

**Comment by EnTeQuAk** [comment]
Marking this as p2 as it's actually blocking any l10n updates, that's not a p1 I think but important enough.

**Comment by EnTeQuAk** [comment]
Submitted upstream patch and wrote current maintainer.

**Comment by EnTeQuAk** [comment]
Followed up with current maintainer, going to fork on Thursday if we don't get a response. That allows translators for some time to follow-up with our translations.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk does this require any QA?
Thanks
