### ISSUE TITLE
Write a python script to generate a UUID for the fxa email within the integration-tests.

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-server#11952]
It seems that the UUID package will randomly not resolve. This add extra flakiness to the integration tests on circleci that really shouldn't exist. We should build a simple python script to generate an fxa email the tests can use.

**Comment by jrbenny35** [comment]
Log of the failure:
```
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/code/src/olympia/landfill/management/commands/generate_default_addons_for_frontend.py", line 80, in handle
    serializer = GenerateAddonsSerializer()
  File "/code/src/olympia/landfill/serializers.py", line 52, in __init__
    self.fxa_id = self._create_fxa_user()
  File "/code/src/olympia/landfill/serializers.py", line 63, in _create_fxa_user
    fxa_account.password)
  File "/usr/local/lib/python3.6/site-packages/fxa/core.py", line 64, in create_account
    resp = self.apiclient.post(url, body)
  File "/usr/local/lib/python3.6/site-packages/fxa/_utils.py", line 335, in post
    return self.request("POST", url, json, **kwds)
  File "/usr/local/lib/python3.6/site-packages/fxa/_utils.py", line 321, in request
    raise fxa.errors.ClientError(body)
fxa.errors.ClientError: Account already exists
Makefile-docker:161: recipe for target 'setup-ui-tests' failed
```
