### ISSUE TITLE
`manage.py cron gc` command not able to finish itself

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#12051]
### Describe the problem and steps to reproduce it:

In #amo channel, cgrebs asked us to check how the daily cron job `manage.py cron gc` runs, so we ran it manually on the command line, and it turned out this command failed because of the following error.

```
{"Timestamp": 1565107215865131008, "Type": "z.cron", "Logger": "http_app_addons", "Hostname": "ip-172-31-45-0", "EnvVersion": "2.0", "Severity": 6, "Pid": 1, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Beginning job: gc []"}}
{"Timestamp": 1565107215865401088, "Type": "z.cron", "Logger": "http_app_addons", "Hostname": "ip-172-31-45-0", "EnvVersion": "2.0", "Severity": 7, "Pid": 1, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Collecting data to delete"}}
{"Timestamp": 1565107216540317440, "Type": "z.cron", "Logger": "http_app_addons", "Hostname": "ip-172-31-45-0", "EnvVersion": "2.0", "Severity": 7, "Pid": 1, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Cleaning up test results extraction cache."}}
^[[C{"Timestamp": 1565108366946441216, "Type": "z.cron", "Logger": "http_app_addons", "Hostname": "ip-172-31-45-0", "EnvVersion": "2.0", "Severity": 7, "Pid": 1, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "b''"}}
{"Timestamp": 1565108366946963968, "Type": "z.cron", "Logger": "http_app_addons", "Hostname": "ip-172-31-45-0", "EnvVersion": "2.0", "Severity": 7, "Pid": 1, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Cleaning up uncompressed userpics."}}
{"Timestamp": 1565108622396351232, "Type": "z.cron", "Logger": "http_app_addons", "Hostname": "ip-172-31-45-0", "EnvVersion": "2.0", "Severity": 7, "Pid": 1, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "b''"}}
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2006, 'MySQL server has gone away')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/data/olympia/src/olympia/amo/management/commands/cron.py", line 40, in handle
    getattr(module, name)(*args)
  File "/data/olympia/src/olympia/amo/cron.py", line 87, in gc
    for file_upload in stale_uploads:
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/data/olympia/src/olympia/amo/models.py", line 47, in _fetch_all
    super(BaseQuerySet, self)._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (2006, 'MySQL server has gone away')
```

### What happened?

`manage.py cron gc` not able to finish itself and failed with the above error.

### What did you expect to happen?

`manage.py cron gc` finishes without errors.

### Anything else we should know?

Before the command failed, we noticed that it's calling the Linux find command like so,

```
root      4446  0.0  0.0   8896  3240 ?        Sl   16:00   0:00      \_ docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/f1136a1eeee427817ebac02bc0311b7edaafebcc6adcb49b9ad7bc317ba3f468 -address /var/run/docker/containerd/docker-containerd.sock -containerd-binary /usr/bin/docker-containerd -runtime-root /var/run/docker/runtime-runc
olympia   4463  0.2  1.2 277864 97564 ?        Ss   16:00   0:02          \_ python -W ignore::DeprecationWarning manage.py cron gc
olympia   4500  1.2  0.3  46332 29332 ?        D    16:00   0:12              \_ find shared_storage/uploads -maxdepth 1 -name validate-* -mtime +7 -type d -exec rm -rf {} ;
```

However the `shared_storage/uploads` is a very big directory with more than 217K sub-directories in it.

We suspect that the DB timeout error was due to the fact that the program spent too much time on the find command, and by the time the find finished, the DB connection had timed out.

We have seen the same DB connection time out error before for a different cron job, see https://github.com/mozilla/addons-server/issues/11464 for details. The method used in that ticket to solve the issue may be useful for this one.

**Comment by diox** [comment]
Inside `gc` function we have:

```python
    log.debug('Cleaning up test results extraction cache.')
    # lol at check for '/'
    if settings.MEDIA_ROOT and settings.MEDIA_ROOT != '/':
        cmd = ('find', settings.MEDIA_ROOT, '-maxdepth', '1', '-name',
               'validate-*', '-mtime', '+7', '-type', 'd',
               '-exec', 'rm', '-rf', "{}", ';')

        output = Popen(cmd, stdout=PIPE).communicate()[0]

        for line in output.split(b'\n'):
            log.debug(line)

    else:
        log.warning('MEDIA_ROOT not defined.')

    USERPICS_PATH = user_media_path('userpics')
    if USERPICS_PATH:
        log.debug('Cleaning up uncompressed userpics.')

        cmd = ('find', USERPICS_PATH,
               '-name', '*__unconverted', '-mtime', '+1', '-type', 'f',
               '-exec', 'rm', '{}', ';')
        output = Popen(cmd, stdout=PIPE).communicate()[0]
```

We should 1) make sure those are still necessary (I'm not sure they are, at least the second one) and 2) move them to a different cron while we figure this out.

**Comment by diox** [comment]
So, after some investigation, it turns out that both are ... completely useless nowadays.

The part of the code that deals with `validate-*` files was introduced 9 years ago for b8423263c07. I can't find any trace of code creating these files in the history of the repos though, and this code seem to be a drive-by addition not relevant to the commit itself, which is about cleaning up collections (and, I guess, ended up being about cleaning everything)

The second one, the `*__unconverted` files, was a thing for user avatar uploads, that got changed in dc9a6678efdb14f3eea2cbac1e6b2bd1859f757e
