### ISSUE TITLE
Landfill returns `fxa.errors.ClientError: Invalid parameter in request body`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13316]
See: https://circleci.com/gh/mozilla/addons-frontend/19164

---

Not sure what's going on but the ui tests in addons-frontend are failing because of this error:

```
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/deps/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/deps/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/deps/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/deps/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/code/src/olympia/landfill/management/commands/generate_default_addons_for_frontend.py", line 80, in handle
    serializer = GenerateAddonsSerializer()
  File "/code/src/olympia/landfill/serializers.py", line 52, in __init__
    self.fxa_id = self._create_fxa_user()
  File "/code/src/olympia/landfill/serializers.py", line 63, in _create_fxa_user
    fxa_account.password)
  File "/deps/lib/python3.6/site-packages/fxa/core.py", line 64, in create_account
    resp = self.apiclient.post(url, body)
  File "/deps/lib/python3.6/site-packages/fxa/_utils.py", line 335, in post
    return self.request("POST", url, json, **kwds)
  File "/deps/lib/python3.6/site-packages/fxa/_utils.py", line 321, in request
    raise fxa.errors.ClientError(body)
fxa.errors.ClientError: Invalid parameter in request body
Makefile-docker:153: recipe for target 'setup-ui-tests' failed
```

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-26
