### ISSUE TITLE
update_counts_from_file job failed on 2020-05-22

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#14369]
### Describe the problem and steps to reproduce it:
The `update_counts_from_file` failed to work today to process the 2020-05-21 data.

### What happened?
We were alerted that the latest update counts are missing for 2020-05-21, when we tried to re-run the `update_counts_from_file` job manually, we see numerous processing errors such as the following:

```
{"Timestamp": 1590186904469298176, "Type": "adi.updatecounts", "Logger": "http_app_addons", "Hostname": "ip-172-31-8-80", "EnvVersion": "2.0", "Severity": 6, "Pid": 1, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Addon ***@***.net doesn't exist."}, "severity": 200}
{"Timestamp": 1590186904469398016, "Type": "adi.updatecounts", "Logger": "http_app_addons", "Hostname": "ip-172-31-8-80", "EnvVersion": "2.0", "Severity": 6, "Pid": 1, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Addon ***@***.org doesn't exist."}, "severity": 200}
{"Timestamp": 1590186904469650688, "Type": "adi.updatecounts", "Logger": "http_app_addons", "Hostname": "ip-172-31-8-80", "EnvVersion": "2.0", "Severity": 6, "Pid": 1, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Addon ***@***.edu doesn't exist."}, "severity": 200}
... ...
{"Timestamp": 1590186909189666816, "Type": "adi.updatecounts", "Logger": "http_app_addons", "Hostname": "ip-172-31-8-80", "EnvVersion": "2.0", "Severity": 6, "Pid": 1, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Addon {ff1f8614-6b3b-42d0-be8d-5c8f27b9daa9} doesn't exist."}, "severity": 200}
{"Timestamp": 1590186909189788928, "Type": "adi.updatecounts", "Logger": "http_app_addons", "Hostname": "ip-172-31-8-80", "EnvVersion": "2.0", "Severity": 6, "Pid": 1, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Addon {ff23e138-f6a6-477b-91e4-cad5f8937621} doesn't exist."}, "severity": 200}
{"Timestamp": 1590186909189938688, "Type": "adi.updatecounts", "Logger": "http_app_addons", "Hostname": "ip-172-31-8-80", "EnvVersion": "2.0", "Severity": 6, "Pid": 1, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Update type doesn't add to 16: 97"}, "severity": 200}
{"Timestamp": 1590186909190038784, "Type": "adi.updatecounts", "Logger": "http_app_addons", "Hostname": "ip-172-31-8-80", "EnvVersion": "2.0", "Severity": 6, "Pid": 1, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Addon {ff356687-aa08-463d-a46c-11c451824939} doesn't exist."}, "severity": 200}
{"Timestamp": 1590186909190153728, "Type": "adi.updatecounts", "Logger": "http_app_addons", "Hostname": "ip-172-31-8-80", "EnvVersion": "2.0", "Severity": 6, "Pid": 1, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Addon {ff3c2153-64d4-6a05-98cd-6108ac2f01c9} doesn't exist."}, "severity": 200}
```

And in the end an exception was thrown,

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 257, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 224, in autocommit
    _mysql.connection.autocommit(self, on)
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/data/olympia/src/olympia/stats/management/commands/update_counts_from_file.py", line 238, in handle
    UpdateCount.objects.bulk_create(update_counts.values(), 100)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 465, in bulk_create
    with transaction.atomic(using=self.db, savepoint=False):
  File "/usr/local/lib/python3.6/site-packages/django/db/transaction.py", line 201, in __enter__
    connection.set_autocommit(False, force_begin_transaction_with_broken_autocommit=True)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 405, in set_autocommit
    self._set_autocommit(autocommit)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 257, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 257, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 224, in autocommit
    _mysql.connection.autocommit(self, on)
django.db.utils.OperationalError: (2013, 'Lost connection to MySQL server during query')
```

 
### What did you expect to happen?
The `update_counts_from_file` should run successfully.

### Anything else we should know?

A couple of notes regarding this issue,

* This job has been successfully running for many months without an error. We had a push yesterday (2020-05-21), and it started to fail. It may be related, or it may be just a coincidence.

*  I suspect the "lost db connection" exception may not be that important in this case. This exception might have be caused by the program having to write many many errors, such as `Addon ***@***.net doesn't exist.`, to the standard output. That is an email address, and not an addon after all.

**Comment by bqbn** [comment]
The same error happened again today (5-23-2020). I looked at the hive results and don't think those have changed. My current bet is this is related to 5/21 release.

**Comment by diox** [comment]
Likely another consequence of https://github.com/mozilla/addons-server/issues/14091, which ironically might have increased the amount of logging we do in some circumstances.

>  This exception might have be caused by the program having to write many many errors, such as `Addon ***@***.net doesn't exist.`, to the standard output. That is an email address, and not an addon after all.

Addon guids have 2 forms, an actual GUID in the form of `{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}` or email-like `foo@bar.tld`, which can even be abbreviated in `@bar`. It's kinda weird that we get many add-on that do not exist, maybe worth looking into. It's likely the problem does come from the extra error logging and we ignored before.

**Comment by bqbn** [comment]
Yeah, confirmed the failure of the command has to do with [[1](https://github.com/mozilla/addons-server/pull/14310/files#diff-51853ffe8cc4db81eb67b8a2830b3e3bR188)] and [[2](https://github.com/mozilla/addons-server/pull/14310/files#diff-51853ffe8cc4db81eb67b8a2830b3e3bR196)].

The previous `debug` level was suppressed by the logger, and changing it to `info` caused tens of thousands of lines (if not more) to be written to standard output and that wasted a lot of time, and by the time it finished, the db connection had timed out.

After manually changing those two lines back to `log.debug` and the command was able to finish successfully.

```
# ./manage.py update_counts_from_file --date 2020-05-21
{"Timestamp": 1590273506169551872, "Type": "adi.updatecounts", "Logger": "http_app_addons", "Hostname": "ip-172-31-8-80", "EnvVersion": "2.0", "Severity": 6, "Pid": 583, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Processed 1000000 lines"}, "severity": 200}
{"Timestamp": 1590273518593694720, "Type": "adi.updatecounts", "Logger": "http_app_addons", "Hostname": "ip-172-31-8-80", "EnvVersion": "2.0", "Severity": 6, "Pid": 583, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Processed 2000000 lines"}, "severity": 200}
{"Timestamp": 1590273533333718016, "Type": "adi.updatecounts", "Logger": "http_app_addons", "Hostname": "ip-172-31-8-80", "EnvVersion": "2.0", "Severity": 6, "Pid": 583, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Processed 1000000 lines"}, "severity": 200}
{"Timestamp": 1590273540939216384, "Type": "adi.updatecounts", "Logger": "http_app_addons", "Hostname": "ip-172-31-8-80", "EnvVersion": "2.0", "Severity": 6, "Pid": 583, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Processed 2000000 lines"}, "severity": 200}
{"Timestamp": 1590273554516160768, "Type": "adi.updatecounts", "Logger": "http_app_addons", "Hostname": "ip-172-31-8-80", "EnvVersion": "2.0", "Severity": 6, "Pid": 583, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Processed 1000000 lines"}, "severity": 200}
{"Timestamp": 1590273637420235776, "Type": "adi.updatecounts", "Logger": "http_app_addons", "Hostname": "ip-172-31-8-80", "EnvVersion": "2.0", "Severity": 6, "Pid": 583, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Processed a total of 907645 lines"}, "severity": 200}
{"Timestamp": 1590273637420523520, "Type": "adi.updatecounts", "Logger": "http_app_addons", "Hostname": "ip-172-31-8-80", "EnvVersion": "2.0", "Severity": 6, "Pid": 583, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Total processing time: 0:02:34.421779"}, "severity": 200}
```

**Comment by bqbn** [comment]
> Likely another consequence of #14091, which ironically might have increased the amount of logging we do in some circumstances.

I didn't look in details what https://github.com/mozilla/addons-server/issues/14091 did. However, what I thought was that the app as a whole allowed only say `INFO` and above level logs, thus if we were to reduce logging volume, we should have made more lines written at `DEBUG` level, so that they're suppressed.

It feels a little strange in this particular case that we changed `log.debug` to `log.info`, which means we output more, and contradict what we want to achieve.

**Comment by diox** [comment]
The idea was that we were previously logging all `DEBUG` messages, so we wanted to start by achieving the same state to start with, while suppressing `DEBUG` messages for the future. And then start changing back some not-so-useful log statements from `info` back to `debug`.

Unfortunately, in some cases we were already suppressing `DEBUG` messages, and so that caused those specific statements to go through instead of being suppressed.

**Comment by diox** [comment]
should be fixed in next tag.

**Comment by bqbn** [comment]
@diox I'm afraid we need to fix https://github.com/mozilla/addons-server/blob/master/src/olympia/stats/management/commands/update_counts_from_file.py#L188 too, because as shown above, there are log lines like this,

```
{"Timestamp": 1590186909189938688, "Type": "adi.updatecounts", "Logger": "http_app_addons", "Hostname": "ip-172-31-8-80", "EnvVersion": "2.0", "Severity": 6, "Pid": 1, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Update type doesn't add to 16: 97"}, "severity": 200}
```

In the manual test I did last Saturday, I made L188 `log.debug` as well.
