### ISSUE TITLE
Error occurs during installation on local environment

### ISSUE THREAD

**Issue by junngo** [mozilla/addons-server#14437]
### Describe the problem and steps to reproduce it:
I tried to install on local through the command below:
```
make initialize
```
I pull the latest source and executed it according to the manual.

### What happened?
Error occurs during installation on local env.
![2020-05-29](https://user-images.githubusercontent.com/29684524/83243492-ef6b0e80-a1d8-11ea-9c7c-db74a9b6b1c9.png)

### What did you expect to happen?
Installation is completed.

### Anything else we should know?
```
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/deps/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/deps/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/deps/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/deps/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/code/src/olympia/landfill/management/commands/generate_default_addons_for_frontend.py", line 80, in handle
    serializer = GenerateAddonsSerializer()
  File "/code/src/olympia/landfill/serializers.py", line 52, in __init__
    self.fxa_id = self._create_fxa_user()
  File "/code/src/olympia/landfill/serializers.py", line 75, in _create_fxa_user
    fxa_account.password)
  File "/deps/lib/python3.6/site-packages/fxa/core.py", line 64, in create_account
    resp = self.apiclient.post(url, body)
  File "/deps/lib/python3.6/site-packages/fxa/_utils.py", line 335, in post
    return self.request("POST", url, json, **kwds)
  File "/deps/lib/python3.6/site-packages/fxa/_utils.py", line 267, in request
    raise fxa.errors.OutOfProtocolError(msg.format(content_type))
fxa.errors.OutOfProtocolError: API responded with non-json content-type: text/html
make: *** [Makefile-docker:90: populate_data] Error 1
Makefile-os:28: recipe for target 'initialize' failed
make: *** [initialize] Error 2
```

**Comment by diox** [comment]
FxA's stable.dev.lcip.org is down and for some reason our initialize step wants actual FxA ids... We should avoid that, but even once we fix it, as long as that service is down you wouldn't be able to log in anyway...

**Comment by junngo** [comment]
Hello diox.
I checked to be build without above error and open `http://olympia.test` page.
