### ISSUE TITLE
Indexing of a newly initialized database fails

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14525]
```
python3 manage.py reindex --wipe --force --noinput
{"Timestamp": 1591287203964317952, "Type": "raven.contrib.django.client.DjangoClient", "Logger": "http_app_addons", "Hostname": "7f3b9e2bb260", "EnvVersion": "2.0", "Severity": 6, "Pid": 1463, "Fields": {"uid": "", "remoteAddressChain": "", "msg": "Raven is not configured (logging is disabled). Please see the documentation for more information."}, "severity": 200}
{"Timestamp": 1591287204023002112, "Type": "raven.base.Client", "Logger": "http_app_addons", "Hostname": "7f3b9e2bb260", "EnvVersion": "2.0", "Severity": 6, "Pid": 1463, "Fields": {"uid": "", "remoteAddressChain": "", "msg": "Raven is not configured (logging is disabled). Please see the documentation for more information."}, "severity": 200}
/deps/lib/python3.6/site-packages/multidb/__init__.py:68: UserWarning: [multidb] No replica databases are configured! You can configure them with the REPLICA_DATABASES setting.
  UserWarning,
Starting the reindexation for addons.
{"Timestamp": 1591287205368356864, "Type": "z.elasticsearch", "Logger": "http_app_addons", "Hostname": "7f3b9e2bb260", "EnvVersion": "2.0", "Severity": 6, "Pid": 1463, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Unflagging the database"}, "severity": 200}
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/deps/lib/python3.6/site-packages/dockerflow/logging.py", line 138, in format
    out = self.convert_record(record)
  File "/code/src/olympia/core/logger.py", line 58, in convert_record
    out = super().convert_record(record)
  File "/deps/lib/python3.6/site-packages/dockerflow/logging.py", line 127, in convert_record
    fields["error"] = repr(record.exc_info[1])
TypeError: 'bool' object is not subscriptable
Call stack:
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/deps/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/deps/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/deps/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/deps/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/code/src/olympia/lib/es/management/commands/reindex.py", line 168, in handle
    index = next(iter(ES.indices.get(alias)))
  File "/deps/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/deps/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 135, in get
    feature), params=params)
  File "/deps/lib/python3.6/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/deps/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self.log_request_fail(method, full_url, url, body, duration, response.status, raw_data)
  File "/deps/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 97, in log_request_fail
    status_code or 'N/A', duration, exc_info=exception is not None
Message: '%s %s [status:%s request:%.3fs]'
Arguments: ('GET', 'http://elasticsearch:9200/addons', 404, 0.12774419784545898)
Building the task chain
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/deps/lib/python3.6/site-packages/dockerflow/logging.py", line 138, in format
    out = self.convert_record(record)
  File "/code/src/olympia/core/logger.py", line 58, in convert_record
    out = super().convert_record(record)
  File "/deps/lib/python3.6/site-packages/dockerflow/logging.py", line 127, in convert_record
    fields["error"] = repr(record.exc_info[1])
TypeError: 'bool' object is not subscriptable
Call stack:
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/deps/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/deps/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/deps/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/deps/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/code/src/olympia/lib/es/management/commands/reindex.py", line 177, in handle
    workflow = self.create_workflow(alias)
  File "/code/src/olympia/lib/es/management/commands/reindex.py", line 196, in create_workflow
    olds = ES.indices.get_alias(alias)
  File "/deps/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/deps/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 399, in get_alias
    '_alias', name), params=params)
  File "/deps/lib/python3.6/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/deps/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self.log_request_fail(method, full_url, url, body, duration, response.status, raw_data)
  File "/deps/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 97, in log_request_fail
    status_code or 'N/A', duration, exc_info=exception is not None
Message: '%s %s [status:%s request:%.3fs]'
Arguments: ('GET', 'http://elasticsearch:9200/addons/_alias', 404, 0.006524562835693359)
{"Timestamp": 1591287205524306432, "Type": "z.elasticsearch", "Logger": "http_app_addons", "Hostname": "7f3b9e2bb260", "EnvVersion": "2.0", "Severity": 6, "Pid": 1463, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Returning reindexing group for addons-20200604161325"}, "severity": 200}
```

// cc @diox

**Comment by diox** [comment]
This looks like a bug in python-dockerflow, I filed it here: https://github.com/mozilla-services/python-dockerflow/issues/46

**Comment by diox** [comment]
f4ac097a7b4 should have fixed this.
