### ISSUE TITLE
Error during compress_assets step

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14522]
While running `manage.py compress_assets`, I get the following error:

```
Parse error at /code/src/olympia/../../static/js/debug-all.js:9183,14
              function hue(h) {
              ^
ERROR: In strict mode code, functions can only be declared at top level or immediately within another function.
    at JS_Parse_Error.get (eval at <anonymous> (/deps/node_modules/uglify-js/tools/node.js:18:1), <anonymous>:71:23)
    at fatal (/deps/node_modules/uglify-js/bin/uglifyjs:334:27)
    at run (/deps/node_modules/uglify-js/bin/uglifyjs:277:9)
    at Object.<anonymous> (/deps/node_modules/uglify-js/bin/uglifyjs:192:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```

**Comment by diox** [comment]
I have seen this for a while. As far I can see, it's harmless: the `debug` bundle fails to compress, but it should never be enabled when `settings.DEBUG` is `True`, and when it's `False`, it's not used unless you force it somehow since we don't need/use concatenated bundles if `settings.DEBUG` is `True`.
