### ISSUE TITLE
Make the `deliver_hotness` task more efficient

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14900]
We should really use something like `chunked()` to not load/instantiate 300K add-ons directly. We could also avoid loading the translations. In addition to that, we could certainly change the task to be asynchronous.

**Comment by bqbn** [comment]
BTW, the manual run of the command failed with the following error.

```
$ ./manage.py cron deliver_hotness
{"Timestamp": 1594316605617230080, "Type": "z.cron", "Logger": "http_app_addons", "Hostname": "ip-172-31-25-45", "EnvVersion": "2.0", "Severity": 6, "Pid": 6, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Beginning job: deliver_hotness [] {} (start timestamp: 1594316605617.134)"}, "severity": 200}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/data/olympia/src/olympia/amo/management/commands/cron.py", line 50, in handle
    getattr(module, name)(*args, **kwargs)
  File "/data/olympia/src/olympia/addons/cron.py", line 202, in deliver_hotness
    addon.update(hotness=hotness)
  File "/data/olympia/src/olympia/amo/models.py", line 254, in update
    self._send_changes(old_attr, kw)
  File "/data/olympia/src/olympia/amo/models.py", line 230, in _send_changes
    instance=_NoChangeInstance(self), sender=self.__class__)
  File "/data/olympia/src/olympia/addons/models.py", line 1592, in watch_status
    channel=amo.RELEASE_CHANNEL_LISTED)
  File "/data/olympia/src/olympia/addons/models.py", line 888, in find_latest_version
    latest = latest_qs.latest()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 649, in latest
    return self.reverse()._earliest(*fields, field_name=field_name)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 643, in _earliest
    return obj.get()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/data/olympia/src/olympia/amo/models.py", line 47, in _fetch_all
    super(BaseQuerySet, self)._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/django/__init__.py", line 487, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (2013, 'Lost connection to MySQL server during query')
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

From past experience, this is usually due to the command taking too much time computing and when it finally came back around, the db connection had timed out.
