### ISSUE TITLE
Getting 500s from the addon signing endpoint

### ISSUE THREAD

**Issue by dacodas** [mozilla/addons-server#17242]
### Please attach a copy of your add-on

[dacoda_themes_work_default-0.2.zip](https://github.com/mozilla/addons/files/6563013/dacoda_themes_work_default-0.2.zip)

### Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

I have tried to both submit a new add-on and submit a new version of an existing add-on submitted via the web UI.

### Whether your add-on is listed or unlisted.

Unlisted

### The URL where you submitted the add-on.

I used the `web-ext` tool.

### Describe the problem and steps to reproduce it:

I am trying to use the `web-ext sign` tool to sign my theme for personal use. When 

```
(dacoda@fedora work λ) web-ext sign --api-key=$( pass Firefox/JWT/Issuer ) --api-secret=$( pass Firefox/JWT/Secret )
Building web extension from /home/dacoda/projects/firefox-themes/work
No extension ID specified (it will be auto-generated)

Error: Received bad response from the server while requesting https://addons.mozilla.org/api/v4/addons/

status: 500
response: {"detail":"Internal Server Error"}
headers: {"allow":"GET, POST, PUT, HEAD, OPTIONS","content-security-policy":"style-src 'self' 'unsafe-inline' https://addons.cdn.mozilla.net; base-uri 'self' https://addons.mozilla.org; script-src https://www.google-analytics.com/analytics.js https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.gstatic.cn/recaptcha/ https://addons.cdn.mozilla.net; form-action 'self'; frame-src 'self' https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/; media-src https://videos.cdn.mozilla.net; object-src 'none'; font-src 'self' https://addons.cdn.mozilla.net; child-src 'self' https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/; connect-src 'self' https://sentry.prod.mozaws.net https://www.google-analytics.com https://addons.cdn.mozilla.net; default-src 'self'; img-src 'self' data: blob: https://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net; report-uri /__cspreport__","content-type":"application/json","date":"Fri, 28 May 2021 19:29:21 GMT","server":"nginx","set-cookie":["multidb_pin_writes=y; expires=Fri, 28 May 2021 19:29:36 GMT; Max-Age=15; Path=/"],"strict-transport-security":"max-age=31536000","vary":"Origin, X-Country-Code, Accept-Language","x-amo-request-id":"a82d3ad7be144b6f827d2ecc2893622b","x-content-type-options":"nosniff","x-frame-options":"DENY","x-xss-protection":"1; mode=block","content-length":"34","connection":"Close"}

    at /home/dacoda/.npm-packages/lib/node_modules/web-ext/node_modules/sign-addon/dist/webpack:/sign-addon/src/amo-client.js:274:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /home/dacoda/.npm-packages/lib/node_modules/web-ext/dist/web-ext.js:1:11436
    at O.execute (/home/dacoda/.npm-packages/lib/node_modules/web-ext/dist/web-ext.js:1:64444)
```

Here is a verbose run. 

```
(dacoda@fedora work λ) web-ext sign --api-key=$( pass Firefox/JWT/Issuer ) --api-secret=$( pass Firefox/JWT/Secret )
Building web extension from /home/dacoda/projects/firefox-themes/work
No extension ID specified (it will be auto-generated)

Error: Received bad response from the server while requesting https://addons.mozilla.org/api/v4/addons/

status: 500
response: {"detail":"Internal Server Error"}
headers: {"allow":"GET, POST, PUT, HEAD, OPTIONS","content-security-policy":"style-src 'self' 'unsafe-inline' https://addons.cdn.mozilla.net; base-uri 'self' https://addons.mozilla.org; script-src https://www.google-analytics.com/analytics.js https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.gstatic.cn/recaptcha/ https://addons.cdn.mozilla.net; form-action 'self'; frame-src 'self' https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/; media-src https://videos.cdn.mozilla.net; object-src 'none'; font-src 'self' https://addons.cdn.mozilla.net; child-src 'self' https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/; connect-src 'self' https://sentry.prod.mozaws.net https://www.google-analytics.com https://addons.cdn.mozilla.net; default-src 'self'; img-src 'self' data: blob: https://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net; report-uri /__cspreport__","content-type":"application/json","date":"Fri, 28 May 2021 19:29:21 GMT","server":"nginx","set-cookie":["multidb_pin_writes=y; expires=Fri, 28 May 2021 19:29:36 GMT; Max-Age=15; Path=/"],"strict-transport-security":"max-age=31536000","vary":"Origin, X-Country-Code, Accept-Language","x-amo-request-id":"a82d3ad7be144b6f827d2ecc2893622b","x-content-type-options":"nosniff","x-frame-options":"DENY","x-xss-protection":"1; mode=block","content-length":"34","connection":"Close"}

    at /home/dacoda/.npm-packages/lib/node_modules/web-ext/node_modules/sign-addon/dist/webpack:/sign-addon/src/amo-client.js:274:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /home/dacoda/.npm-packages/lib/node_modules/web-ext/dist/web-ext.js:1:11436
    at O.execute (/home/dacoda/.npm-packages/lib/node_modules/web-ext/dist/web-ext.js:1:64444)

(dacoda@fedora work λ) web-ext sign -vvv --api-key=$( pass Firefox/JWT/Issuer ) --api-secret=$( pass Firefox/JWT/Secret )
[program.js][info] Version: 6.1.0
[program.js][debug] Discovering config files. Set --no-config-discovery to disable
[config.js][debug] Discovered config "/home/dacoda/.web-ext-config.js" does not exist or is not readable
[config.js][debug] Discovered config "/home/dacoda/projects/firefox-themes/work/package.json" does not exist or is not readable
[config.js][debug] Discovered config "/home/dacoda/projects/firefox-themes/work/web-ext-config.js" does not exist or is not readable
[util/temp-dir.js][debug] Created temporary directory: /tmp/tmp-web-ext--343259-ZOowgTxM1nVV
[util/manifest.js][debug] Validating manifest at /home/dacoda/projects/firefox-themes/work/manifest.json
[util/file-filter.js][debug] Resolved path **/*.xpi with sourceDir /home/dacoda/projects/firefox-themes/work to /home/dacoda/projects/firefox-themes/work/**/*.xpi
[util/file-filter.js][debug] Resolved path **/*.zip with sourceDir /home/dacoda/projects/firefox-themes/work to /home/dacoda/projects/firefox-themes/work/**/*.zip
[util/file-filter.js][debug] Resolved path **/.* with sourceDir /home/dacoda/projects/firefox-themes/work to /home/dacoda/projects/firefox-themes/work/**/.*
[util/file-filter.js][debug] Resolved path **/.*/**/* with sourceDir /home/dacoda/projects/firefox-themes/work to /home/dacoda/projects/firefox-themes/work/**/.*/**/*
[util/file-filter.js][debug] Resolved path **/node_modules with sourceDir /home/dacoda/projects/firefox-themes/work to /home/dacoda/projects/firefox-themes/work/**/node_modules
[util/file-filter.js][debug] Resolved path **/node_modules/**/* with sourceDir /home/dacoda/projects/firefox-themes/work to /home/dacoda/projects/firefox-themes/work/**/node_modules/**/*
[cmd/build.js][info] Building web extension from /home/dacoda/projects/firefox-themes/work
[cmd/sign.js][debug] No ID file found at: /home/dacoda/projects/firefox-themes/work/.web-extension-id
[cmd/build.js][debug] Using manifest id=[not specified]
[util/file-filter.js][debug] Resolved path /home/dacoda/projects/firefox-themes/work/manifest.json with sourceDir /home/dacoda/projects/firefox-themes/work to /home/dacoda/projects/firefox-themes/work/manifest.json
[util/file-filter.js][debug] Resolved path /home/dacoda/projects/firefox-themes/work/text.png with sourceDir /home/dacoda/projects/firefox-themes/work to /home/dacoda/projects/firefox-themes/work/text.png
[util/file-filter.js][debug] Resolved path /home/dacoda/projects/firefox-themes/work/web-ext-artifacts with sourceDir /home/dacoda/projects/firefox-themes/work to /home/dacoda/projects/firefox-themes/work/web-ext-artifacts
[util/file-filter.js][debug] Resolved path /home/dacoda/projects/firefox-themes/work/web-ext-artifacts/dacoda_themes_work_default-0.2.zip with sourceDir /home/dacoda/projects/firefox-themes/work to /home/dacoda/projects/firefox-themes/work/web-ext-artifacts/dacoda_themes_work_default-0.2.zip
[util/file-filter.js][debug] FileFilter: ignoring file /home/dacoda/projects/firefox-themes/work/web-ext-artifacts/dacoda_themes_work_default-0.2.zip
[cmd/sign.js][warn] No extension ID specified (it will be auto-generated)
[sign-addon] Signing add-on without an ID
[sign-addon] [API] POST request:
 {
  url: 'https://addons.mozilla.org/api/v4/addons/',
  formData: {
    upload: {
      _readableState: [Object],
      _events: [Object],
      _eventsCount: 1,
      _maxListeners: undefined,
      path: '/tmp/tmp-web-ext--343259-ZOowgTxM1nVV/dacoda_themes_work_default-0.2.zip',
      fd: null,
      flags: 'r',
      mode: 438,
      start: undefined,
      end: Infinity,
      autoClose: true,
      pos: undefined,
      bytesRead: 0,
      closed: false,
      [Symbol(kFs)]: [Object],
      [Symbol(kCapture)]: false,
      [Symbol(kIsPerformingIO)]: false
    },
    version: '0.2'
  },
  timeout: 300500,
  headers: { Authorization: '<REDACTED>', Accept: 'application/json' }
}
[sign-addon] [API] POST response:
 Status: 500
 {
  headers: {
    allow: 'GET, POST, PUT, HEAD, OPTIONS',
    'content-security-policy': "object-src 'none'; form-action 'self'; base-uri 'self' https://addons.mozilla.org; child-src 'self' https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/; script-src https://www.google-analytics.com/analytics.js https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.gstatic.cn/recaptcha/ https://addons.cdn.mozilla.net; default-src 'self'; style-src 'self' 'unsafe-inline' https://addons.cdn.mozilla.net; font-src 'self' https://addons.cdn.mozilla.net; frame-src 'self' https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/; connect-src 'self' https://sentry.prod.mozaws.net https://www.google-analytics.com https://addons.cdn.mozilla.net; media-src https://videos.cdn.mozilla.net; img-src 'self' data: blob: https://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net; report-uri /__cspreport__",
    'content-type': 'application/json',
    date: 'Fri, 28 May 2021 19:30:04 GMT',
    server: 'nginx',
    'set-cookie': '<REDACTED>',
    'strict-transport-security': 'max-age=31536000',
    vary: 'Origin, X-Country-Code, Accept-Language',
    'x-amo-request-id': '39e830273ba54fa5ab882c86ed2ffdae',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'DENY',
    'x-xss-protection': '1; mode=block',
    'content-length': '34',
    connection: 'Close'
  },
  response: { detail: 'Internal Server Error' }
}
[util/temp-dir.js][debug] Removing temporary directory: /tmp/tmp-web-ext--343259-ZOowgTxM1nVV
[program.js][error] 
Error: Received bad response from the server while requesting https://addons.mozilla.org/api/v4/addons/

status: 500
response: {"detail":"Internal Server Error"}
headers: {"allow":"GET, POST, PUT, HEAD, OPTIONS","content-security-policy":"object-src 'none'; form-action 'self'; base-uri 'self' https://addons.mozilla.org; child-src 'self' https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/; script-src https://www.google-analytics.com/analytics.js https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.gstatic.cn/recaptcha/ https://addons.cdn.mozilla.net; default-src 'self'; style-src 'self' 'unsafe-inline' https://addons.cdn.mozilla.net; font-src 'self' https://addons.cdn.mozilla.net; frame-src 'self' https://www.google.com/recaptcha/ https://www.recaptcha.net/recaptcha/; connect-src 'self' https://sentry.prod.mozaws.net https://www.google-analytics.com https://addons.cdn.mozilla.net; media-src https://videos.cdn.mozilla.net; img-src 'self' data: blob: https://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net; report-uri /__cspreport__","content-type":"application/json","date":"Fri, 28 May 2021 19:30:04 GMT","server":"nginx","set-cookie":["multidb_pin_writes=y; expires=Fri, 28 May 2021 19:30:19 GMT; Max-Age=15; Path=/"],"strict-transport-security":"max-age=31536000","vary":"Origin, X-Country-Code, Accept-Language","x-amo-request-id":"39e830273ba54fa5ab882c86ed2ffdae","x-content-type-options":"nosniff","x-frame-options":"DENY","x-xss-protection":"1; mode=block","content-length":"34","connection":"Close"}

    at /home/dacoda/.npm-packages/lib/node_modules/web-ext/node_modules/sign-addon/dist/webpack:/sign-addon/src/amo-client.js:274:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /home/dacoda/.npm-packages/lib/node_modules/web-ext/dist/web-ext.js:1:11436
    at O.execute (/home/dacoda/.npm-packages/lib/node_modules/web-ext/dist/web-ext.js:1:64444)

[program.js][debug] Command executed: sign
```

I also tried using the `v5` API endpoint using the following `bash` and Node scripts. I gleaned the Node code from what I saw in the `amo-client.js` file that was installed when I installed `web-ext`.

```
(dacoda@fedora work λ) cat ../sign 
#!/bin/bash

export NODE_PATH=/home/dacoda/.npm-packages/lib/node_modules/web-ext/node_modules

jwt_token() {
	pushd ../node-testing/ &> /dev/null
	node src/main.js
}

test_new_version() {
	curl "https://addons.mozilla.org/api/v5/addons/34aad543ee5349408adb/versions/0.2/" \
		-g -XPUT --form "upload=@web-ext-artifacts/dacoda_themes_work_default-0.2.zip" \
		-H "Authorization: JWT $( jwt_token )"
}

test_new_extension() {
	curl "https://addons.mozilla.org/api/v5/addons/" \
		-g -XPOST --form "upload=@web-ext-artifacts/dacoda_themes_work_default-0.2.zip" -F "version=0.2" \
		-H "Authorization: JWT $( jwt_token )"
}

test_new_version
test_new_extension
```

```
(dacoda@fedora work λ) cat ../node-testing/src/main.js 
let child_process = require("child_process");
let jsonwebtoken = require("jsonwebtoken");

function passHelper(path) {

	let child = child_process.spawnSync(
		'pass', [path]
	);

	return child.stdout.toString('utf8').trim()
}

const apiKey = passHelper('Firefox/JWT/Issuer');
const apiSecret = passHelper('Firefox/JWT/Secret');

const authToken = jsonwebtoken.sign({ iss: apiKey }, apiSecret, {
     algorithm: 'HS256',
     expiresIn: 5 * 60
});

console.log(authToken)
```

Here are the results. In this case, I was throttled, but I indeed got the 500 in both tests.

```
(dacoda@fedora work λ) bash ../sign 
+ bash ../sign
+ export NODE_PATH=/home/dacoda/.npm-packages/lib/node_modules/web-ext/node_modules
+ NODE_PATH=/home/dacoda/.npm-packages/lib/node_modules/web-ext/node_modules
+ test_new_version
++ jwt_token
++ pushd ../node-testing/
++ node src/main.js
+ curl https://addons.mozilla.org/api/v5/addons/34aad543ee5349408adb/versions/0.2/ -g -XPUT --form upload=@web-ext-artifacts/dacoda_themes_work_default-0.2.zip -H 'Authorization: JWT REDACTED'
{"detail":"Internal Server Error"}
+ test_new_extension
++ jwt_token
++ pushd ../node-testing/
++ node src/main.js
+ curl https://addons.mozilla.org/api/v5/addons/ -g -XPOST --form upload=@web-ext-artifacts/dacoda_themes_work_default-0.2.zip -F version=0.2 -H 'Authorization: JWT REDACTED'
{"detail":"Request was throttled. Expected available in 44 seconds."}
```

### What happened?

I received a 500 from the server.

### What did you expect to happen?

I expected a more verbose error message to lead me to troubleshooting more quickly.

### Anything else we should know?

I think that is good.

**Comment by willdurand** [comment]
I found this error in Sentry: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/11116369/?query=is%3Aunresolved, it looks like we attempt to get the size of an `InMemoryUploadedFile` with some `os` functions. I think we should either not call `os.path.getsize()` or dump the in-memory content on disk beforehand.

**Comment by willdurand** [comment]
The code was added in https://github.com/mozilla/addons-server/pull/9305 fwiw.

**Comment by eviljeff** [comment]
we can use `InMemoryUploadedFile.size`

**Comment by diox** [comment]
QA: try submitting a small (< 2.5 MB zip), large (> 2.5 MB zip) and extra large (> 7MB) theme with the API and with devhub. The small and large should succeed, the extra large should return a validation error (as per #9305).

**Comment by dacodas** [comment]
Thanks, y'all!!

**Comment by ioanarusiczki** [comment]
@diox nevermind, I just found what's been causing this with Postman, looks like the Content-type multipart/form-data is a default now, but I was adding it manually into Headers and it was causing a 500. I got now a 201 response so I'll continue testing.

**Comment by ioanarusiczki** [comment]
@diox 
1. I made several POST requests for https://addons-dev.allizom.org/api/v5/addons/ with JWT Authorization:
- 201 Created for themes in all cases except for >7MB when I get a 400 "Maximum size for WebExtension themes is 7.0MB." 
- the error message is also present and validation will not pass for a theme >7MB(zip). Except for that, dev hub submissions are working. 
2. I sent some PUT requests submitting new versions without errors (202 status) for listed and unlisted versions. An example: https://addons-dev.allizom.org/api/v5/addons/{b2fcd54b-f4aa-4bdf-9511-325c231eb99c}/versions/7.0/

3. I did see that requests to -stage  https://addons.allizom.org/api/v5/addons/  are not possible for themes, where I got a 500 server error trying to submit the samples that worked for me on -dev which proves the issue is fixed now.
