### ISSUE TITLE
make initialize_docker fails

### ISSUE THREAD

**Issue by Natim** [mozilla/addons-server#1952]
```
r$ make initialize_docker
docker exec -t -i "addonsserver_web_1" make initialize_docker_inner
python manage.py reset_db
No handlers could be found for logger "product_details"
Raven is not configured (logging is disabled). Please see the documentation for more information.
12:08:01 z.startup:INFO Product details missing, downloading... :/code/src/olympia/core/apps.py:52
Grabbing list of JSON files from the server from https://svn.mozilla.org/libs/product-details/json/
12:08:01 prod_details:DEBUG Grabbing list of JSON files from the server from https://svn.mozilla.org/libs/product-details/json/ :/usr/lib/python2.7/site-packages/product_details/management/commands/update_product_details.py:61
No last update timestamp found.
12:08:01 prod_details:INFO No last update timestamp found. :/usr/lib/python2.7/site-packages/product_details/management/commands/update_product_details.py:100
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/code/src/olympia/core/apps.py", line 36, in ready
    self.load_product_details()
  File "/code/src/olympia/core/apps.py", line 53, in load_product_details
    call_command('update_product_details')
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/usr/lib/python2.7/site-packages/product_details/management/commands/update_product_details.py", line 53, in handle_noargs
    self.download_directory()
  File "/usr/lib/python2.7/site-packages/product_details/management/commands/update_product_details.py", line 63, in download_directory
    json_files = self.get_file_list(dir)
  File "/usr/lib/python2.7/site-packages/product_details/management/commands/update_product_details.py", line 106, in get_file_list
    if e.code == httplib.NOT_MODIFIED:
AttributeError: 'URLError' object has no attribute 'code'

```

**Comment by Natim** [comment]
Here is what I had to do to fix it:

```
diff --git a/src/olympia/core/apps.py b/src/olympia/core/apps.py
index 14f511a..e79626c 100644
--- a/src/olympia/core/apps.py
+++ b/src/olympia/core/apps.py
@@ -50,5 +50,5 @@ class CoreConfig(AppConfig):
         if not product_details.last_update:
 
             log.info('Product details missing, downloading...')
-            call_command('update_product_details')
-            product_details.__init__()  # reload the product details
+            # call_command('update_product_details')
+            # product_details.__init__()  # reload the product details
```

**Comment by Natim** [comment]
The version of django-mozilla-product-details in use in the docker image seems outdated.

**Comment by Natim** [comment]
The problem was fixed as soon as the Internet connection got better.
This error was fixed in recent version of ``django-mozilla-product-details`` that are not compatible with Django 1.7
