### ISSUE TITLE
"none" and "all" links under Account Settings-> User Notifications don't work

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2016]
## steps to reproduce:
1. Sign in to AMO and load https://addons-dev.allizom.org/en-US/firefox/users/edit
2. Click on "none" or "all" under User Notifications

## observed behavior:
Functionality is broken

## sentry link: 
https://sentry.prod.mozaws.net/operations/frontend-dev/group/251280/

## traceback details:
Stacktrace (most recent call first):

  at b</oe.error (/static/js/preload-min.js:1:13265)
  at b</oe.tokenize (/static/js/preload-min.js:1:19537)
  at oe (/static/js/preload-min.js:1:7389)
  at .find (/static/js/preload-min.js:1:25066)
  at ? (/static/js/impala-min.js:8:20325)
  at _pd/< (/static/js/impala-min.js:2:20)
  at n (/static/js/impala-min.js:1:12223)
  at p.event.dispatch (/static/js/preload-min.js:2:14382)
  at p.event.add/y.handle (/static/js/preload-min.js:2:10960)
  at EventListener.handleEvent*p.event.add (/static/js/preload-min.js:2:11484)
  at i.event.add (/static/js/impala-min.js:1:13283)
  at ve/< (/static/js/preload-min.js:2:10628)
  at .each (/static/js/preload-min.js:1:3039)
  at p.prototype.each (/static/js/preload-min.js:1:901)
  at ve (/static/js/preload-min.js:2:10610)
  at .on (/static/js/preload-min.js:2:20688)
  at p.fn[t] (/static/js/preload-min.js:3:19761)
  at ? (/static/js/impala-min.js:8:20263)
  at n (/static/js/impala-min.js:1:12223)
  at p.Callbacks/u (/static/js/preload-min.js:1:28568)
  at p.Callbacks/l.fireWith (/static/js/preload-min.js:1:29405)
  at EventListener.handleEvent*p.ready.promise (/static/js/preload-min.js:1:31797)
  at ? (/static/js/preload-min.js:2:148)
  at ? (/static/js/preload-min.js:1:221)
  at ? (/static/js/preload-min.js:1:2)

**Comment by ValentinaPC** [comment]
Please note that the same issue is also logged in Bugzilla, under: https://bugzilla.mozilla.org/show_bug.cgi?id=1221984 . Thanks!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45 (Win 7).
Postfix screencast: http://screencast.com/t/Pf1oqmwZ
