### ISSUE TITLE
The "cron gc" command fails to run in the GCP dev environment

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#20859]
### Describe the problem and steps to reproduce it:
The "cron gc" command fails to run in the GCP dev environment with the following error,

```
$ python -W ignore::DeprecationWarning manage.py cron gc
{"Timestamp": 1687293338029215232, "Type": "z.cron", "Logger": "http_app_addons_dev", "Hostname": "addons-server-v1-deploy-uwsgi-amo-web-d7b8fd9d7-ktcb5", "EnvVersion": "2.0", "Severity": 6, "Pid": 25, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Beginning job: gc [] {} (start timestamp: 1687293338029.1392)"}, "severity": 200}
{"Timestamp": 1687293338030695936, "Type": "z.cron", "Logger": "http_app_addons_dev", "Hostname": "addons-server-v1-deploy-uwsgi-amo-web-d7b8fd9d7-ktcb5", "EnvVersion": "2.0", "Severity": 6, "Pid": 25, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Collecting data to delete"}, "severity": 200}
{"Timestamp": 1687293338338046720, "Type": "z.cron", "Logger": "http_app_addons_dev", "Hostname": "addons-server-v1-deploy-uwsgi-amo-web-d7b8fd9d7-ktcb5", "EnvVersion": "2.0", "Severity": 6, "Pid": 25, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "[FileUpload:2039366e-ec37-4e05-8a37-a9dc7161bf83] Removing file: /mnt/efs/addons-dev.allizom.org/files/temp/096c5ae3b0234efb82ceb18edf244ba1.zip"}, "severity": 200}
Traceback (most recent call last):
  File "/data/olympia/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/deps/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/deps/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/deps/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/deps/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/data/olympia/src/olympia/amo/management/commands/cron.py", line 51, in handle
    getattr(module, name)(*args, **kwargs)
  File "/data/olympia/src/olympia/amo/cron.py", line 63, in gc
    storage.delete(file_upload.path)
  File "/deps/lib/python3.10/site-packages/django/core/files/storage/filesystem.py", line 152, in delete
    name = self.path(name)
  File "/data/olympia/src/olympia/amo/utils.py", line 882, in path
    return os.path.normpath(super().path(force_str(name)))
  File "/deps/lib/python3.10/site-packages/django/core/files/storage/filesystem.py", line 179, in path
    return safe_join(self.location, name)
  File "/deps/lib/python3.10/site-packages/django/utils/_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (/mnt/efs/addons-dev.allizom.org/files/temp/096c5ae3b0234efb82ceb18edf244ba1.zip) is located outside of the base path component (/mnt/filestore/addons-server)
```

### What happened?
It turns out the `file_uploads` table has entries that contains the full path instead of relying on the `NETAPP_STORAGE_ROOT` to construct the path.

And the `cron gc` command fails on the first error.

### What did you expect to happen?
Ideally, the `cron gc` should not fail on the `SuspiciousFileOperation` error but continue with the next candidate file.

Another thing to do is come up with a SQL command to update the `path` column in the `file_uploads` table with the new path prefix (i.e. `/mnt/filestore/addons-server`).

### Anything else we should know?
n/a

**Comment by diox** [comment]
Ran this on dev:

```
>>> FileUpload.objects.filter(path__startswith='/mnt/efs').update(
path=Replace('path', Value('/mnt/efs/addons-server/files'), Value('/mnt/filestore/addons-server/files')))
217

>>> FileUpload.objects.filter(path__startswith='/mnt/efs').update(
path=Replace('path', Value('/mnt/efs/addons-dev.allizom.org/files'), Value('/mnt/filestore/addons-server/files')))
45
```

Then fired the cron again, it worked.

**Comment by bqbn** [comment]
Perfect! Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-407
