### ISSUE TITLE
Reinindexing in Circle CI regularly fails to complete

### ISSUE THREAD

**Issue by davehunt** [mozilla/addons-server#2706]
A lot of the time my Circle CI builds (for running the UI tests) are timing out whilst reindexing. An example is https://circleci.com/gh/davehunt/addons-server/35 (output snipped below):

```
...
11:17:52 z.task:INFO [1@50/m] Updating review denorms. :/code/src/olympia/reviews/tasks.py:22
11:17:52 z.task:INFO [1@50/m] Updating review denorms. :/code/src/olympia/reviews/tasks.py:22
11:17:53 z.task:INFO [1@50/m] Updating review denorms. :/code/src/olympia/reviews/tasks.py:22
11:17:53 z.task:INFO [1@50/m] Updating review denorms. :/code/src/olympia/reviews/tasks.py:22
11:17:53 z.task:INFO [1@50/m] Updating review denorms. :/code/src/olympia/reviews/tasks.py:22
python manage.py reindex --wipe --force --noinput
Raven is not configured (logging is disabled). Please see the documentation for more information.
11:17:56 z.startup:INFO Set RECURSION_LIMIT to 10000 :/code/src/olympia/core/apps.py:76
Starting the reindexation
Unflagging the database
Building the task tree
Running all indexation tasks
....................................
```

There is a potentially correlating exception in the ES log:

```
$ docker logs addonsserver_elasticsearch_1
[2016-05-19 11:13:49,085][INFO ][node                     ] [Mac Gargan] version[1.3.9], pid[1], build[0915c73/2015-02-19T12:34:48Z]
[2016-05-19 11:13:49,092][INFO ][node                     ] [Mac Gargan] initializing ...
[2016-05-19 11:13:49,104][INFO ][plugins                  ] [Mac Gargan] loaded [], sites []
[2016-05-19 11:13:53,535][INFO ][node                     ] [Mac Gargan] initialized
[2016-05-19 11:13:53,536][INFO ][node                     ] [Mac Gargan] starting ...
[2016-05-19 11:13:55,016][INFO ][transport                ] [Mac Gargan] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/172.17.0.3:9300]}
[2016-05-19 11:13:55,115][INFO ][discovery                ] [Mac Gargan] elasticsearch/enlWpuQzR9SKt_YpzOZOpg
[2016-05-19 11:13:58,196][INFO ][cluster.service          ] [Mac Gargan] new_master [Mac Gargan][enlWpuQzR9SKt_YpzOZOpg][6ba44be0e109][inet[/172.17.0.3:9300]], reason: zen-disco-join (elected_as_master)
[2016-05-19 11:13:58,306][INFO ][gateway                  ] [Mac Gargan] recovered [0] indices into cluster_state
[2016-05-19 11:13:58,530][INFO ][http                     ] [Mac Gargan] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/172.17.0.3:9200]}
[2016-05-19 11:13:58,531][INFO ][node                     ] [Mac Gargan] started
[2016-05-19 11:16:05,489][INFO ][cluster.metadata         ] [Mac Gargan] [addons] creating index, cause [auto(bulk api)], shards [5]/[1], mappings []
[2016-05-19 11:16:09,623][INFO ][cluster.metadata         ] [Mac Gargan] [addons] update_mapping [users] (dynamic)
[2016-05-19 11:16:09,849][INFO ][cluster.metadata         ] [Mac Gargan] [addons] update_mapping [collections] (dynamic)
[2016-05-19 11:16:09,987][INFO ][cluster.metadata         ] [Mac Gargan] [addons] update_mapping [addons] (dynamic)
[2016-05-19 11:16:33,909][INFO ][cluster.metadata         ] [Mac Gargan] [addons] update_mapping [addons] (dynamic)
[2016-05-19 11:17:01,121][INFO ][cluster.metadata         ] [Mac Gargan] [addons] update_mapping [addons] (dynamic)
[2016-05-19 11:17:28,125][INFO ][cluster.metadata         ] [Mac Gargan] [addons] update_mapping [addons] (dynamic)
[2016-05-19 11:17:50,356][INFO ][cluster.metadata         ] [Mac Gargan] [addons] update_mapping [addons] (dynamic)
[2016-05-19 11:17:56,968][INFO ][cluster.metadata         ] [Mac Gargan] [addons] deleting index
[2016-05-19 11:17:57,337][INFO ][cluster.metadata         ] [Mac Gargan] [addons] creating index, cause [auto(bulk api)], shards [5]/[1], mappings []
[2016-05-19 11:17:57,715][INFO ][cluster.metadata         ] [Mac Gargan] [addons] update_mapping [addons] (dynamic)
[2016-05-19 11:17:58,499][INFO ][cluster.metadata         ] [Mac Gargan] [addons] update_mapping [collections] (dynamic)
[2016-05-19 11:18:07,708][INFO ][cluster.metadata         ] [Mac Gargan] [addons-20160519111757] creating index, cause [auto(bulk api)], shards [5]/[1], mappings []
[2016-05-19 11:18:08,275][INFO ][cluster.metadata         ] [Mac Gargan] [addons-20160519111757] update_mapping [addons] (dynamic)
[2016-05-19 11:18:11,571][INFO ][cluster.metadata         ] [Mac Gargan] [addons-20160519111757] update_mapping [users] (dynamic)
[2016-05-19 11:18:11,778][INFO ][cluster.metadata         ] [Mac Gargan] [addons-20160519111757] update_mapping [collections] (dynamic)
[2016-05-19 11:18:12,202][INFO ][cluster.metadata         ] [Mac Gargan] [addons-20160519111757] update_mapping [addons] (dynamic)
[2016-05-19 11:18:12,376][DEBUG][action.admin.indices.alias] [Mac Gargan] failed to perform aliases
org.elasticsearch.indices.InvalidAliasNameException: [addons-20160519111757] Invalid alias name [addons], an index exists with the same name as the alias
	at org.elasticsearch.cluster.metadata.AliasValidator.validateAlias(AliasValidator.java:102)
	at org.elasticsearch.cluster.metadata.AliasValidator.validateAliasAction(AliasValidator.java:53)
	at org.elasticsearch.cluster.metadata.MetaDataIndexAliasesService$1.execute(MetaDataIndexAliasesService.java:77)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:328)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:184)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by diox** [comment]
We're discussing this on IRC. 

What is happening:
- `make populate_data` generates some add-ons
- elasticsearch aliases are not set up yet, so ES creates an `addons` index with a dynamic mapping
- We then call `reindex` and it fails because the `addons` alias is not an alias but an index instead.

It's interesting, because I thought calling `reindex --wipe` would prevent the `Invalid alias name [addons], an index exists with the same name as the alias` error, since it's supposed to well, wipe before reindexing.

**Comment by diox** [comment]
Note to self: also need to call `manage.py cron category_totals` when done generating.

**Comment by diox** [comment]
@davehunt could you test https://github.com/mozilla/addons-server/pull/2746/files ?

**Comment by davehunt** [comment]
I cherry-picked it to my branch, and it's running here: https://circleci.com/gh/davehunt/addons-server/43

**Comment by diox** [comment]
That build timed out but @davehunt restarted it and it worked : https://circleci.com/gh/davehunt/addons-server/45

I merged my PR into master.
