### ISSUE TITLE
Validation of test webextension fails with Unhandled error during validation: ValueError('end is out of bounds',)

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2778]
## test add-on:  
http://cl.ly/000R3Q3T173i

## steps to reproduce:
1. Upload the test add-on to https://addons-dev.allizom.org/en-US/developers/addon/submit/2

## observed behavior:
Validation fails with unexpected error - https://addons-dev.allizom.org/en-US/developers/upload/aa4adb661b794cdc9750861b71742b8d

## error:
```python
Unhandled error during validation: ValueError('end is out of bounds',) :/data/olympia/src/olympia/devhub/tasks.py:139#012Traceback (most recent call last):#012 File "/data/olympia/src/olympia/devhub/tasks.py", line 129, in wrapper#012 data = fn(id_, hash_, *args, **kw)#012 File "/data/olympia/src/olympia/devhub/tasks.py", line 157, in validate_file_path#012 return run_addons_linter(path, listed=listed)#012 File "/data/olympia/src/olympia/devhub/tasks.py", line 461, in run_addons_linter#012 parsed_data = json.loads(output)#012 File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads#012 return _default_decoder.decode(s)#012 File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode#012 obj, end = self.raw_decode(s, idx=_w(s, 0).end())#012 File "/usr/lib64/python2.7/json/decoder.py", line 381, in raw_decode#012 obj, end = self.scan_once(s, idx)#012ValueError: end is out of bounds
```

**Comment by vcarciu** [comment]
Verified as fixed : 
![krupabug](https://cloud.githubusercontent.com/assets/1583842/15607010/5e09c446-2418-11e6-86a7-2f4793ca7ce1.png)
