### ISSUE TITLE
Errors when trying to use ElasticSearch v2.3.3 for AMO

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#2850]
Filing this bug after talking to @diox.

When trying to upgrade amo-dev to ElasticSearch v2.3.3, we ran into the following errors and the indexes were not created after running "manage.py reindex" command.

```
[2016-06-02 21:05:29,963][DEBUG][action.admin.indices.create] [i-62e57cf8] [addons_dev-20160602210529] failed to create
MapperParsingException[Failed to parse mapping [addons]: Mapping definition for [tags] has unsupported parameters:  [index_name : tag]]; nested: MapperParsingException[Mapping definition for [tags] has unsupported parameters:  [index_name : tag]];
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$1.execute(MetaDataCreateIndexService.java:332)
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
        at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: MapperParsingException[Mapping definition for [tags] has unsupported parameters:  [index_name : tag]]
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:171)
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:165)
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:307)
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:218)
        at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:139)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:118)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:99)
        at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:508)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:288)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$1.execute(MetaDataCreateIndexService.java:329)
        ... 8 more
```

Please help resolve this so that amo supports ElasticSearch v2.3.3. Please also see if the ElasticSearch client libs can be upgraded as well.

**Comment by diox** [comment]
A few more errors pop up once `tags` and `platforms` mapping are fixed:

`MapperParsingException[failed to parse]; nested: IllegalStateException[Mixing up field types: class org.elasticsearch.index.mapper.core.IntegerFieldMapper$IntegerFieldType != class org.elasticsearch.index.mapper.core.ByteFieldMapper$ByteFieldType on field type];`

and 

`java.lang.IllegalArgumentException: [current_version] is defined as a field in mapping [compat] but this name is already used for an object in other types`

which is strange since `current_version` should not be in `compat` mapping.

**Comment by diox** [comment]
It also looks like even when mapping creation works it fails to install the necessary alias...

**Comment by diox** [comment]
`compat.current_version` clash is because of a change in ES. The suggestion is to use a different name... https://discuss.elastic.co/t/how-to-solve-field-in-mapping-but-already-used-in-other-types/43067

**Comment by diox** [comment]
We have some code using facets, that will completely fail with ES 2.x and the queries need to be replaced by [aggregation queries](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/search-aggregations.html) (which work with 1.6 too).

**Comment by bqbn** [comment]
@diox could you share where we are regarding this issue? Just trying to get a sense of timeline here.

**Comment by diox** [comment]
I fixed as many of the issues I could while still being backwards-compatible. I think it should the upgrade should work, or at least can be attempted again on dev, even with the older client libs for the time being. Do warn us in advance if you do this, though, as we rely on dev for testing. Let me know if you run into issues.

**Comment by bqbn** [comment]
@diox I switched to v2.3.3 on -dev and ran ```manage.py reindex``` again. Good news is that this time I don't see errors in elasticsearch logs. However, when running the ```manage.py cron index_latest_stats```, it did throw out this error:
```
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 97, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, {u'index': u'addons_stats_dev', u'resource.type': u'index_or_alias', u'root_cause': [{u'index': u'addons_stats_dev', u'reason': u'no such index', u'type': u'index_not_found_exception', u'resource.id': u'addons_stats_dev', u'resource.type': u'index_or_alias'}], u'reason': u'no such index', u'type': u'index_not_found_exception', u'resource.id': u'addons_stats_dev'})
```
Besides, the search function on the website doesn't seem to work after switching to the new cluster.

I've switched back to the old cluster for now. Let me know when you want to troubleshoot this so I can switch it to the new version again.

**Comment by bqbn** [comment]
Some more info. With the app pointing to the new cluster with version v2.3.3, here is the output for ```manage.py reindex```:
```
[olympia@ip-172-31-15-180 olympia]$ ./manage.py reindex
No handlers could be found for logger "z.files.utils"
Starting the reindexation
Building the task chain
Running all indexation tasks
......

*** Reindexation done ***

Reindexed 1 indexes.

Current Aliases configuration:

{
    "addons_dev-20161017225145": {
        "aliases": {}
    },
    "addons_dev-20161017231316": {
        "aliases": {
            "addons_dev": {}
        }
    }
}
```
And here is the some info from the new cluster after running the above "reindex" command:
```
$ curl -XGET 'http://localhost:9200/_cluster/health?pretty=true'
{
  "cluster_name" : "elasticsearch-amodev1-20161017-3.amo.us-east-1.dev",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 4,
  "number_of_data_nodes" : 4,
  "active_primary_shards" : 10,
  "active_shards" : 25,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}

$ curl 'localhost:9200/_cat/indices/*'
green open addons_dev-20161017225145 5 1 275850 0 965.9mb 495.5mb
green open addons_dev-20161017231316 5 2      0 0   2.3kb    795b

$ curl localhost:9200/_cat/shards
addons_dev-20161017225145 2 p STARTED 38679 51.2mb 172.31.60.7  i-0f59ed93d4fd423a5
addons_dev-20161017225145 2 r STARTED 38679 51.5mb 172.31.7.160 i-0f680ad0e6a395452
addons_dev-20161017225145 3 r STARTED 38700 51.2mb 172.31.32.95 i-06efbba7de89a833b
addons_dev-20161017225145 3 p STARTED 38700 69.1mb 172.31.7.160 i-0f680ad0e6a395452
addons_dev-20161017225145 4 p STARTED 38685 52.2mb 172.31.29.53 i-0df52615d1e15ec1f
addons_dev-20161017225145 4 r STARTED 38685 52.3mb 172.31.60.7  i-0f59ed93d4fd423a5
addons_dev-20161017225145 1 p STARTED 38547 58.2mb 172.31.32.95 i-06efbba7de89a833b
addons_dev-20161017225145 1 r STARTED 38547 50.5mb 172.31.60.7  i-0f59ed93d4fd423a5
addons_dev-20161017225145 0 p STARTED 38439 50.5mb 172.31.29.53 i-0df52615d1e15ec1f
addons_dev-20161017225145 0 r STARTED 38439 50.7mb 172.31.32.95 i-06efbba7de89a833b
addons_dev-20161017231316 2 r STARTED     0   130b 172.31.29.53 i-0df52615d1e15ec1f
addons_dev-20161017231316 2 r STARTED     0   130b 172.31.60.7  i-0f59ed93d4fd423a5
addons_dev-20161017231316 2 p STARTED     0   130b 172.31.7.160 i-0f680ad0e6a395452
addons_dev-20161017231316 3 r STARTED     0   130b 172.31.29.53 i-0df52615d1e15ec1f
addons_dev-20161017231316 3 p STARTED     0   130b 172.31.32.95 i-06efbba7de89a833b
addons_dev-20161017231316 3 r STARTED     0   130b 172.31.7.160 i-0f680ad0e6a395452
addons_dev-20161017231316 4 p STARTED     0   130b 172.31.29.53 i-0df52615d1e15ec1f
addons_dev-20161017231316 4 r STARTED     0   130b 172.31.32.95 i-06efbba7de89a833b
addons_dev-20161017231316 4 r STARTED     0   130b 172.31.60.7  i-0f59ed93d4fd423a5
addons_dev-20161017231316 1 r STARTED     0   130b 172.31.32.95 i-06efbba7de89a833b
addons_dev-20161017231316 1 p STARTED     0   130b 172.31.60.7  i-0f59ed93d4fd423a5
addons_dev-20161017231316 1 r STARTED     0   130b 172.31.7.160 i-0f680ad0e6a395452
addons_dev-20161017231316 0 p STARTED     0   130b 172.31.29.53 i-0df52615d1e15ec1f
addons_dev-20161017231316 0 r STARTED     0   130b 172.31.60.7  i-0f59ed93d4fd423a5
addons_dev-20161017231316 0 r STARTED     0   130b 172.31.7.160 i-0f680ad0e6a395452
```

**Comment by bqbn** [comment]
We'll be upgrading to ES v5 directly. Closing this.
