### ISSUE TITLE
Error when trying to run `make initialize_docker`

### ISSUE THREAD

**Issue by Natim** [mozilla/addons-server#3057]
<details>
  <summary>Traceback</summary>
```
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/deps/src/jingo-minify/jingo_minify/management/commands/compress_assets.py", line 113, in handle
    self.update_hashes(options.get('add_timestamp', False))
  File "/deps/src/jingo-minify/jingo_minify/management/commands/compress_assets.py", line 42, in update_hashes
    id = git.repo.Repo(path).log('-1')[0].id_abbrev
  File "/usr/lib/python2.7/site-packages/git/repo.py", line 273, in log
    return Commit.list_from_string(self, commits)
  File "/usr/lib/python2.7/site-packages/git/commit.py", line 178, in list_from_string
    author, authored_date = cls.actor(lines.pop(0))
  File "/usr/lib/python2.7/site-packages/git/commit.py", line 288, in actor
    actor, epoch = m.groups()
AttributeError: 'NoneType' object has no attribute 'groups'
make[1]: *** [update_assets] Error 1
make[1]: Leaving directory `/code'
make: *** [initialize_docker_inner] Error 2
Makefile:198 : la recette pour la cible « initialize_docker » a échouée
make: *** [initialize_docker] Erreur 2
```
</details>

**Comment by EnTeQuAk** [comment]
Yeah, I ran into that problem some time ago. You're using verified git commits which breaks GitPython. My unfortunate response to that would be to not use verified git commits for the time being until we got rid of jingo-minify and with that GitPython :crying_cat_face:

**Comment by Natim** [comment]
Oh it help thanks, I can probably deactivate it for that project.

**Comment by EnTeQuAk** [comment]
Not for too long hopefully. Thank you so much :)
