### ISSUE TITLE
Cannot register a new user using local docker

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#3772]
### Describe the problem and steps to reproduce it:

Using a local docker instance:
* Make sure you're signed out
* Click Register
* Sign in via Firefox Accounts with a new email (one that you haven't registered before)
* After confirming the email, wait for the redirect

### What happened?

I get this traceback every time, with different emails.

````
"Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/src/olympia/amo/decorators.py", line 161, in wrapper
    return f(*args, **kw)
  File "/code/src/olympia/amo/decorators.py", line 148, in __call__
    return self.f(*args, **kw)
  File "/code/src/olympia/accounts/views.py", line 245, in inner
    next_path=next_path)
  File "/code/src/olympia/accounts/views.py", line 350, in get
    register_user(request, identity)
  File "/code/src/olympia/accounts/views.py", line 100, in register_user
    email=identity['email'], username=None, fxa_id=identity['uid'])
  File "/code/src/olympia/users/models.py", line 91, in create_user
    user.save(using=self._db)
  File "/code/src/olympia/amo/models.py", line 269, in save
    result = super(OnChangeMixin, self).save(*args, **kw)
  File "/code/src/olympia/amo/models.py", line 405, in save
    return super(ModelBase, self).save(**kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1364, "Field 'confirmationcode' doesn't have a default value")
"
````

### What did you expect to happen?

It should show the profile page and ask me to declare a display name

### Anything else we should know?

Registration seems to be working fine on `addons-dev.allizom.org`

**Comment by kumar303** [comment]
@mstriemer any tips on how to fix this? Is my DB messed up? I recently rebuilt my Docker and am up to date on the latest migrations.

**Comment by mstriemer** [comment]
I think I likely regressed this in https://github.com/mozilla/addons-server/pull/3629/files#diff-22a458b09e44d87c545832b4b7e39484L185. I had dropped the column and field and then ended up leaving the column and should have put the field back.
