### ISSUE TITLE
"manage.py reindex --with-stats" failed to finish on a new ES cluster

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#3960]
### Describe the problem and steps to reproduce it:

This has to do with https://github.com/mozilla/addons-server/issues/2850. Basically we're trying to upgrade ES to v2.3.3, so we created a new cluster with that version, and tried to run "reindex --with-stats" to populate the cache.

1. create a new ES cluster
2. run "manage.py reindex --with-stats --force --wipe"
3. the command never returns and seems to be stuck in the while loop at https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/es/management/commands/reindex.py#L233-L236

### What happened?
We created a new v2.3.3 ES cluster and ran "manage.py reindex --with-stats --force --wipe" to populate the new cluster. However, the command never returned and we had to CTRL+C to get out of it.

Additionally, the reindex command didn't create either the "addons_dev" or the "addons_stats_dev" alias.

Here is the command output:

```
# ./manage.py reindex --with-stats --force --wipe
No handlers could be found for logger "z.files.utils"
Starting the reindexation
Unflagging the database
Building the task chain
Running all indexation tasks
....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................^CTraceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/data/olympia/src/olympia/lib/es/management/commands/reindex.py", line 236, in handle
    time.sleep(5)
KeyboardInterrupt
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

Here is the query for aliases in ES:

```
$ curl http://localhost:9200/_aliases?pretty
{
  "addons_stats_dev-20161107223316" : {
    "aliases" : { }
  },
  "addons_stats_dev-20161107220311" : {
    "aliases" : { }
  },
  "addons_stats_dev-20161108075407" : {
    "aliases" : { }
  },
  "addons_dev" : {
    "aliases" : { }
  },
  "addons_dev-20161108075407" : {
    "aliases" : { }
  },
  "addons_dev-20161107220311" : {
    "aliases" : { }
  },
  "addons_dev-20161107223316" : {
    "aliases" : { }
  }
}
```
As can be seen from above, something created the "addons_dev" index, which should have been an alias instead.

### What did you expect to happen?
The reindex command should end successfully when running against a brand new ES cluster and cache should be populated correctly (for example the aliases should be created correctly).

### Anything else we should know?

1. There are a couple Sentry events were generated when we press the CTRL+C button, and they are here: https://sentry.prod.mozaws.net/operations/olympia-dev/issues/366007/
2. The cron jobs weren't stopped where the reindex command was running. Not sure if it has any effect on this (for example, the creation of the "addons_dev" index).

**Comment by bqbn** [comment]
Some additional information to help troubleshooting:

1. We tried the "reindex" command three times with the following timelines:
```
  11/07 22:03 with "manage.py reindex --with-stats"
  11/07 22:33 with "manage.py reindex --with-stats --wipe --force"
  11/08 07:54 with "manage.py reindex --with-stats --force"
```
2. We found the logs when the "addons_dev" index was created:
```
[2016-11-08 02:30:26,634][INFO ][cluster.metadata         ] [i-0dcc72bc08f5a02fe] [addons_dev] creating index, cause [auto(delete api)], templates [], shards [5]/[1], mappings []
[2016-11-08 02:30:27,390][INFO ][cluster.routing.allocation] [i-0dcc72bc08f5a02fe] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[addons_dev][2], [addons_dev][3], [addons_dev][0], [addons_dev][4], [addons_dev][1]] ...]).
[2016-11-08 02:30:28,339][INFO ][cluster.routing.allocation] [i-0dcc72bc08f5a02fe] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[addons_dev][4], [addons_dev][4], [addons_dev][1]] ...]).
```
There is no log to tell what caused it to be created though.

**Comment by bqbn** [comment]
I tried to run "reindex" against a brand new ES cluster again, and made sure this time, no admin cron job was running during the process. 

Good news is that this time, the "addons_dev" index wasn't created (which seems to suggest that last time it was one of the cron jobs that created that index when the alias didn't exist). However, the whole "reindex" operation still stuck  in the while loop at https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/es/management/commands/reindex.py#L233-L236

The command output looks like this:
```
[olympia@00269d5b0ffb olympia]$ ./manage.py reindex --with-stats --force
No handlers could be found for logger "z.files.utils"
Starting the reindexation
Unflagging the database
Building the task chain
Running all indexation tasks
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```
I watched all rabbitmq queues (including the priority and stats queues) had dropped to zero size and made sure no activities on any of the celery nodes, and waited nearly an hour, then re-checked the queue size was still zero, and no activities on celeries. However, the above command just kept waiting...

Bottom line is I highly doubt the tasks below and including https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/es/management/commands/reindex.py#L204 had a chance to run.

It was only until I manually removed the two rows from zadmin_reindexing table, then the reindex command finally returned. The end result in the ES cluster looks like this:

```
$ curl http://localhost:9200/_aliases?pretty
{
  "addons_stats_dev-20161113201713" : {
    "aliases" : { }
  },
  "addons_dev-20161113201713" : {
    "aliases" : { }
  }
}
```
As can be seen from the above, the two aliases were not created.

During the whole process, there are 1 warning and 3 errors I could find in Celery.

The warning is about "Soft time limit (1800s) exceeded". 

```
Nov 13 20:47:14 ip-172-31-52-188 http_app_addons_dev: [][] celery.worker.job:WARNING Soft time limit (1800s) exceeded for olympia.lib.es.management.commands.reindex.index_data[ea0c75de-9e14-40ab-8702-0965124b65e7] :/usr/lib/python2.7/site-packages/celery/worker/job.py:365
```

The errors are:

```
Nov 13 20:51:32 ip-172-31-52-188 http_app_addons_dev: [<anon>][None] z.task:ERROR Celery TASK exception: ProgrammingError: (2014, "Commands out of sync; you can't run this command now") :/data/olympia/src/olympia/amo/celery.py:61
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/data/olympia/src/olympia/lib/es/management/commands/reindex.py", line 78, in index_data
    get_modules()[alias].reindex(index)
  File "/data/olympia/src/olympia/stats/search.py", line 156, in reindex
    call_command('index_stats', index=index_name)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/data/olympia/src/olympia/stats/management/commands/index_stats.py", line 105, in handle
    '%s__range' % date_field: date_range})),
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 1217, in iterator
    for row in compiler.results_iter():
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 794, in results_iter
    results = self.execute_sql(MULTI)
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 842, in execute_sql
    cursor.close()
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 100, in close
    while self.nextset(): pass
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 132, in nextset
    nr = db.next_result()
ProgrammingError: (2014, "Commands out of sync; you can't run this command now")
```
```
Nov 13 20:51:37 ip-172-31-52-188 http_app_addons_dev: [][] celery.backends.base:ERROR Chord '5dcd63ab-8cd5-40b4-ad2d-319b8dab498e' raised: "TimeoutError('Operation timed out (3.0)',)" :/usr/lib/python2.7/
site-packages/celery/backends/base.py:590
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/backends/base.py", line 583, in on_chord_part_return
    culprit = nex
t(deps._failed_join_report())
StopIteration
```
```
Nov 13 20:51:37 ip-172-31-52-188 http_app_addons_dev: [][] celery.worker.job:ERROR Task olympia.lib.es.management.commands.reindex.index_data[ea0c75de-9e14-40ab-8702-0965124b65e7] raised unexpected: ProgrammingError(2014, "Commands out of sync; you can't run this command now") :/usr/lib/python2.7/site-packages/celery/utils/log.py:282
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/data/olympia/src/olympia/lib/es/management/commands/reindex.py", line 78, in index_data
    get_modules()[alias].reindex(index)
  File "/data/olympia/src/olympia/stats/search.py", line 156, in reindex
    call_command('index_stats', index=index_name)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/data/olympia/src/olympia/stats/management/commands/index_stats.py", line 105, in handle
    '%s__range' % date_field: date_range})),
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 1217, in iterator
    for row in compiler.results_iter():
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 794, in results_iter
    results = self.execute_sql(MULTI)
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 842, in execute_sql
    cursor.close()
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 100, in close
    while self.nextset(): pass
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 132, in nextset
    nr = db.next_result()
ProgrammingError: (2014, "Commands out of sync; you can't run this command now")
```

Let me know if the above helps, and if other info is needed.

Thanks!

**Comment by diox** [comment]
I think it'd be interesting to try again from scratch without the `--with-stats`. I'm not sure `--with-stats` can complete correctly on dev atm when starting from scratch.

**Comment by diox** [comment]
In related news, in the current 1.x ES cluster on dev:
```
"addons_stats_dev-20151012143817": {
        "aliases": {
            "addons_stats_dev": {}
        }
    }
```

So it looks like `reindex --with-stats` worked on dev... a year ago. Not sure what kind of data we had in place then.

**Comment by bqbn** [comment]
We'll be upgrading to ES v5 directly. Closing this.

**Comment by EnTeQuAk** [comment]
This is closed but for documentation:

So the `ProgrammingError: (2014, "Commands out of sync; you can't run this command now")` theoretically (we're about to verify that) came from us calling `call_command('index_stats', ...)` inside a celery-task. `call_command` resets transactions and does quite a few other magic things so I extracted the relevant code into a method that get's now directly called. Hopefully that fixes at least this error and get's us to the next one.
