### ISSUE TITLE
New images fail to run `make initalize_docker`

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#4186]
### Describe the problem and steps to reproduce it:
I updated my images, got a 502 error, and figured I'd just reset my DB. I ran `make initialize_docker` and got this error:

```
~/Projects/addons-server[enable-kab-locale-4179❗ ]% make initialize_docker
docker exec -t -i "addonsserver_web_1" make initialize_docker_inner
make initialize_db update_assets populate_data
make[1]: Entering directory `/code'
rm -rf ./user-media/* ./tmp/*
python manage.py reset_db
No handlers could be found for logger "z.files.utils"
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/code/src/olympia/translations/__init__.py", line 8, in <module>
    do_dictsort(settings.LANGUAGES)]
  File "/usr/lib/python2.7/site-packages/jinja2/filters.py", line 223, in do_dictsort
    return sorted(value.items(), key=sort_func)
  File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 135, in __wrapper__
    res = func(*self.__args, **self.__kw)
  File "/code/src/olympia/lib/settings_base.py", line 179, in lazy_langs
    for i in languages])
KeyError: 'kab'
make[1]: *** [initialize_db] Error 1
make[1]: Leaving directory `/code'
make: *** [initialize_docker_inner] Error 2
make: *** [initialize_docker] Error 2
```

I also removed the docker images and created them from scratch, ran the command again, and got the same output.

### What happened?

I got the error.

### What did you expect to happen?

It to work 😉

**Comment by EnTeQuAk** [comment]
Can you show me a diff on what you changed  to add the `kab` locale?

**Comment by tofumatt** [comment]
Oh no, this fails without any change. This happens on master, sorry for the confusion.

**Comment by tofumatt** [comment]
OMG wait I saw the error about `z.files.logger` and thought that was it. I find Python tracebacks hard to immediately grok.

Seems adding `'kab',` to the list of `AMO_LANGUAGES` in https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/settings_base.py#L156 causes the `KeyError`. I changed it and it worked, I'm useless! 😢

**Comment by diox** [comment]
> OMG wait I saw the error about z.files.logger and thought that was it.

That's #3706, and it's been so annoying that I've just pushed a PR to deal with it.

**Comment by tofumatt** [comment]
So this was clearly an issue between keyboard and chair.
