### ISSUE TITLE
Make initialize_docker fails

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#5371]
Setting up addons-server via docker on a new machine, the `make initialize_docker` command fails with:

```
python manage.py import_prod_versions
13:20:35 z.startup:INFO Set RECURSION_LIMIT to 10000 :/code/src/olympia/core/apps.py:82
13:20:36 raven.base.Client:DEBUG Configuring Raven for host: <raven.conf.remote.RemoteConfig object at 0x3d96390> :/usr/lib/python2.7/site-packages/raven/base.py:255
13:20:36 raven.base.Client:INFO Raven is not configured (logging is disabled). Please see the documentation for more information. :/usr/lib/python2.7/site-packages/raven/base.py:202
Import versions for firefox
Import versions for thunderbird
Import versions for android
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/code/src/olympia/applications/management/commands/import_prod_versions.py", line 18, in handle
    app = APP_GUIDS[codes[i].text]
KeyError: '{a23983c0-fd0e-11dc-95ff-0800200c9a66}'
make[1]: *** [initialize_db] Error 1
make[1]: Leaving directory `/code'
make: *** [initialize_docker_inner] Error 2
make: *** [initialize_docker] Error 2
```

Possibly caused by: https://github.com/mozilla/addons-server/commit/2c487211d24c5a61a325de3ec6dbca676d255e6e

**Comment by diox** [comment]
Should automatically fix itself tomorrow when we push, but I'm going to make the script more robust anyway.

**Comment by muffinresearch** [comment]
FWIW as a workaround, reverting temporarily the patch here [1] allowed the initialization step to complete.


[1] https://github.com/mozilla/addons-server/commit/2c487211d24c5a61a325de3ec6dbca676d255e6e
