### ISSUE TITLE
make initialize_docker fails

### ISSUE THREAD

**Issue by harry-7** [mozilla/addons-server#6066]
I followed the steps listed in [install docs](https://addons-server.readthedocs.io/en/latest/topics/install/docker.html) for setting up development environment with docker. When I was executing `make initialize_docker` it failed with the following error.
```
File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/migration.py", line 112, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 183, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/usr/lib/python2.7/site-packages/product_details/migrations/0002_auto_20151006_1348.py", line 11, in load_json_file_data
    'ProductDetailsFile'))
  File "/usr/lib/python2.7/site-packages/product_details/storage.py", line 286, in json_file_data_to_db
    PDModel.objects.bulk_create(pd_objects)
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 389, in bulk_create
    self._batched_insert(objs_with_pk, fields, batch_size)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 937, in _batched_insert
    using=self.db)
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/lib/python2.7/site-packages/raven/contrib/django/client.py", line 114, in execute
    return real_execute(self, sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
django.db.utils.IntegrityError: (1048, "Column 'last_modified' cannot be null")
make: *** [initialize_db] Error 1
Makefile-os:45: recipe for target 'initialize_docker' failed
make: *** [initialize_docker] Error 2  
```

This is detailed log.
[log.txt](https://github.com/mozilla/addons-server/files/1188084/result.txt)

**Comment by wagnerand** [comment]
Can you pull the latest code and try again, please?

**Comment by EnTeQuAk** [comment]
@wagnerand we're trying to debug this in IRC right now, we're getting close, that error is resolved and the next one should be straight forward. I'll post the fixes here once we get everything running.

**Comment by wagnerand** [comment]
We solved this in IRC, thanks to @EnTeQuAk. Iirc, he's going to follow up with a post-mortem.

**Comment by EnTeQuAk** [comment]
So the problem was as far as we found out a few stale `django-mozilla-product-details` files which we removed and re-synced which eventually fixed the problem described here:

 * (outside container) look for `src/olympia/lib/product_json` folder
 * (outside container)  remove all `*.json` files in there: `rm -rf src/olympia/lib/product_json/*`
 * (outside container)  restore the `readme.md` file again: `git checkout src/olympia/lib/product_json/readme.txt`
 * (inside container) Now resync product detail json files: `python manage.py update_product_details` which takes a few moments to finish

These steps fixed the problem described here.

**Comment by VishalCR7** [comment]
@EnTeQuAk  I ran into same problem and tried same steps. However it gave this error :

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vishal/addons-server/settings.py", line 10, in <module>
    from olympia.lib.settings_base import *  # noqa
ImportError: No module named olympia.lib.settings_base


What should I do next?

**Comment by harry-7** [comment]
can you provide the contents of olympia/lib folder?

**Comment by EnTeQuAk** [comment]
You're not running the management command **inside** the docker container. Something like `docker-compose exec web python manage.py update_product_details` should do it.

**Comment by VishalCR7** [comment]
Yeah that was the problem. It was my first time using docker so didn't understand the meaning of 'inside the docker'. Thanks @EnTeQuAk
