### ISSUE TITLE
Unhiding disabled files cronjob fails

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6654]
From the kibana log:

```
Could not unhide file: /mnt/efs/addons-dev.allizom.org/guarded-addons/417200/language_pack-24.0-fx.xpi.

:/data/olympia/src/olympia/addons/cron.py:234
#012Traceback (most recent call last):
#012 File "/data/olympia/src/olympia/addons/cron.py", line 228, in unhide_disabled_files
#012 .get(version__addon=addon, filename=filename))
#012 File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 338, in get
#012 (self.model._meta.object_name, num)
#012MultipleObjectsReturned: get() returned more than one File -- it returned 2!
```

**Comment by diox** [comment]
Note that itt's inside a `try...except`, so although it's failing for this add-on, it does not prevent the cron from working entirely.
