### ISSUE TITLE
"./manage.py download_counts_from_file" command fails with an error

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#6886]
### Describe the problem and steps to reproduce it:
When running ```./manage.py download_counts_from_file --date <YYYY-MM-DD>``` to restore download counts for a date, the command fails with an error.

### What happened?
For example,
```
$ time sudo docker run --rm --net host -e DJANGO_SETTINGS_MODULE=settings_local -e NETAPP_STORAGE_ROOT='/var/tmp/stats' -e LANG=en_US.UTF-8 -e LC_ALL=en_US.UTF-8 -v /data/olympia/settings_local.py:/data/olympia/settings_local.py:ro -v /etc/olympia:/etc/olympia:ro -v /data/aeskeys:/data/aeskeys:ro -v /var/tmp/stats:/var/tmp/stats:rw hub.prod.mozaws.net/pipelines/addons-server:2017.11.09 python -W ignore::DeprecationWarning manage.py download_counts_from_file --date 2017-11-07
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/data/olympia/src/olympia/stats/management/commands/download_counts_from_file.py", line 162, in handle
    DownloadCount.objects.bulk_create(download_counts.values(), 100)
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 382, in bulk_create
    with transaction.atomic(using=self.db, savepoint=False):
  File "/usr/lib/python2.7/site-packages/django/db/transaction.py", line 186, in __enter__
    connection.set_autocommit(False)
  File "/usr/lib/python2.7/site-packages/django/db/backends/base/base.py", line 295, in set_autocommit
    self._set_autocommit(autocommit)
  File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 301, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/usr/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 301, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 257, in autocommit
    _mysql.connection.autocommit(self, on)
django.db.utils.OperationalError: (2006, 'MySQL server has gone away')
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit

real    56m3.631s
user    0m0.333s
sys     0m0.018s
```

One thing to note is usually it doesn't take this long to finish. Also there was no OOM when this happened. CPU usage was very high when running it.

I've tried to restore download counts for 2017-11-06, 2017-11-07 and 2017-11-08, and they all failed with the same error.

### What did you expect to happen?
No error, and the command returns successfully.

### Anything else we should know?

This affects the statistics on the website. At least the daily download counts won't be available when this happens. Besides, Ops can't restore the data either, because when we re-run the command, it fails.

**Comment by diox** [comment]
@bqbn : There is a setting controlling for how long django keeps a connection opened before trying to re-establish a new one. We haven't had issues with that setting in web workers (it's set to `300` seconds), but maybe there is something different about the instance where this runs?

Wild theory: MySQL is configured to drop inactive connections before 300 seconds, but we never see the problem with web worker threads because we're always keeping the connection active.

**Comment by bqbn** [comment]
This happens on the admin instance where the cron job runs. Specifically, it's this cron [1]. The cron probably failed. And the above output was from me manually running the cron job.

The admin instance, as you know, installs the same app version and configs as the web workers. If you let me know what environment variable I can pass to the app to override the default, I can try it again

It's strange though, that it took about 60 minutes for it to fail if the connection timeout is 300 seconds.

[1]  https://github.com/mozilla/addons-server/blob/master/scripts/crontab/crontab.tpl#L56

**Comment by bqbn** [comment]
The cron failed to process download_counts for 2017-11-13. The log looks like this:

```
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]: Traceback (most recent call last):
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:   File "manage.py", line 11, in <module>
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:     execute_from_command_line(sys.argv)
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:   File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:     utility.execute()
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:   File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:     self.fetch_command(subcommand).run_from_argv(self.argv)
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:   File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:     self.execute(*args, **cmd_options)
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:   File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:     output = self.handle(*args, **options)
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:   File "/data/olympia/src/olympia/stats/management/commands/download_counts_from_file.py", line 162, in handle
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:     DownloadCount.objects.bulk_create(download_counts.values(), 100)
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:   File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:   File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 382, in bulk_create
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:     with transaction.atomic(using=self.db, savepoint=False):
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:   File "/usr/lib/python2.7/site-packages/django/db/transaction.py", line 186, in __enter__
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:     connection.set_autocommit(False)
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:   File "/usr/lib/python2.7/site-packages/django/db/backends/base/base.py", line 295, in set_autocommit
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:     self._set_autocommit(autocommit)
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:   File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 301, in _set_autocommit
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:     self.connection.autocommit(autocommit)
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:   File "/usr/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:     six.reraise(dj_exc_type, dj_exc_value, traceback)
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:   File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 301, in _set_autocommit
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:     self.connection.autocommit(autocommit)
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:   File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 257, in autocommit
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]:     _mysql.connection.autocommit(self, on)
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]: django.db.utils.OperationalError: (2006, 'MySQL server has gone away')
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]: Sentry is attempting to send 1 pending error messages
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]: Waiting up to 10 seconds
Nov 15 00:18:02 ip-172-31-37-109 docker-current[2061]: Press Ctrl-C to quit
```

**Comment by diox** [comment]
It probably spent way too much time (~ 60 minutes) preparing the data that it was supposed to send... Maybe we can force django to create a new connection when sending the data.

(Alternatively, it may be because we just send too much or spend too much time sending it. `wait_timeout` and `max_allowed_packet` would help in that case, but it's probably best to try to handle this in django first)

**Comment by diox** [comment]
This might help: https://github.com/django/django/blob/feac4c30ce7635e17ce1adc4c2c7a1eb0721aeb3/django/db/__init__.py#L62

**Comment by bqbn** [comment]
The cron failed to process download_counts for 2017-11-14 as well.

However, it did succeeded for 2017-11-15. And when it ran successfully, it only took about 2 minutes, it looks like.

```
{"EnvVersion": "2.0", "Type": "adi.downloadcountsfromfile", "Severity": 6, "Fields": {"message": "Processed a total of 57949 lines", "remoteAddressChain": "", "uid": "<anon>"}, "Timestamp": 1510876394365691904, "Logger": "http_app_addons", "Hostname": "ip-172-31-13-12", "Pid": 1}
{"EnvVersion": "2.0", "Type": "adi.downloadcountsfromfile", "Severity": 7, "Fields": {"message": "Total processing time: 0:02:09.035412", "remoteAddressChain": "", "uid": "<anon>"}, "Timestamp": 1510876394366064128, "Logger": "http_app_addons", "Hostname": "ip-172-31-13-12", "Pid": 1}
{"EnvVersion": "2.0", "Type": "adi.downloadcountsfromfile", "Severity": 7, "Fields": {"message": "Deleting /var/tmp/stats/shared_storage/tmp/hive_results/2017-11-15/download_counts.hive", "remoteAddressChain": "", "uid": "<anon>"}, "Timestamp": 1510876394366269184, "Logger": "http_app_addons", "Hostname": "ip-172-31-13-12", "Pid": 1}
```

**Comment by EnTeQuAk** [comment]
@bqbn does this work now properly on production for you?
