### ISSUE TITLE
monitor_fxa_sqs command fails with an error on -dev and -stage

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#7973]
### Describe the problem and steps to reproduce it:

The monitor_fxa_sqs command fails with an error on -dev and -stage as below:

```
Apr 03 16:49:28 ip-172-31-3-56 systemd[1]: Started Monitor Fxa SQS.
Apr 03 16:49:31 ip-172-31-3-56 docker[20945]: {"EnvVersion": "2.0", "Type": "accounts.sqs", "Severity": 6, "Fields": {"msg": "Processing account events from https://sqs.us-east-1.amazonaws.com/927034868273/amo-account-change-dev", "remoteAddressChain": "", "uid": "<anon>"}, "Timestamp": 1522774171552036096, "Logger": "http_app_addons_dev", "Hostname": "ip-172-31-3-56", "Pid": 1}
Apr 03 16:49:31 ip-172-31-3-56 docker[20945]: {"EnvVersion": "2.0", "Type": "accounts.sqs", "Severity": 3, "Fields": {"msg": "Error while processing account events: You must specify a region.", "remoteAddressChain": "", "traceback": "Uncaught exception:\n  File \"/data/olympia/src/olympia/accounts/utils.py\", line 120, in process_sqs_queue\n    sqs = boto3.client('sqs')\n  File \"/usr/local/lib/python2.7/site-packages/boto3/
Apr 03 16:49:31 ip-172-31-3-56 docker[20945]: p_addons_dev", "Hostname": "ip-172-31-3-56", "Pid": 1}
Apr 03 16:49:31 ip-172-31-3-56 docker[20945]: Traceback (most recent call last):
Apr 03 16:49:31 ip-172-31-3-56 docker[20945]: File "./manage.py", line 11, in <module>
Apr 03 16:49:31 ip-172-31-3-56 docker[20945]: execute_from_command_line(sys.argv)
Apr 03 16:49:31 ip-172-31-3-56 docker[20945]: File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
Apr 03 16:49:31 ip-172-31-3-56 docker[20945]: utility.execute()
Apr 03 16:49:31 ip-172-31-3-56 docker[20945]: File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
Apr 03 16:49:31 ip-172-31-3-56 docker[20945]: self.fetch_command(subcommand).run_from_argv(self.argv)
Apr 03 16:49:31 ip-172-31-3-56 docker[20945]: File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
Apr 03 16:49:31 ip-172-31-3-56 docker[20945]: self.execute(*args, **cmd_options)
Apr 03 16:49:31 ip-172-31-3-56 docker[20945]: File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
Apr 03 16:49:31 ip-172-31-3-56 docker[20945]: output = self.handle(*args, **options)
Apr 03 16:49:31 ip-172-31-3-56 docker[20945]: File "/data/olympia/src/olympia/accounts/management/commands/monitor_fxa_sqs.py", line 30, in handle
Apr 03 16:49:31 ip-172-31-3-56 docker[20945]: process_sqs_queue(queue_url)
Apr 03 16:49:31 ip-172-31-3-56 docker[20945]: File "/data/olympia/src/olympia/accounts/utils.py", line 141, in process_sqs_queue
Apr 03 16:49:31 ip-172-31-3-56 docker[20945]: raise exc
Apr 03 16:49:31 ip-172-31-3-56 docker[20945]: botocore.exceptions.NoRegionError: You must specify a region.
```

### What happened?
AFAICT, it may have to do with https://github.com/mozilla/addons-server/pull/7966.

### What did you expect to happen?
No error when the command runs.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by eviljeff** [comment]
QA:
check the FxA email updating added in #6451 still works on -dev.  Checking both scenarios for -dev probably isn't necessary - it'll either be working or it won't.

(#7941 adds the settings for -stage)

**Comment by AlexandraMoga** [comment]
I've retested this on AMO-dev, with the scenarios from #6451 and the user email is still updating as expected, based on the primary email set in FxA page. 

Stage seems to be having issues, but those are mentioned in #7941
