### ISSUE TITLE
Check for updates is not working on -dev and stage

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#8447]
### Describe the problem and steps to reproduce it:
Install an version of extension that is not the latest and try to update it to the latest version.

### What happened?
1528278842164    addons.update-checker    WARN    Request failed: https://versioncheck.allizom.org/update/VersionCheck.php?reqVersion=2&id={e0635c55-2d9c-4939-b3c1-3a28458aa2a3}&version=1.0&maxAppVersion=undefined&status=userEnabled&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=62.0a1&appOS=WINNT&appABI=x86_64-msvc&locale=en-US&currentAppVersion=62.0a1&updateType=97&compatMode=normal - 500: Internal Server Error

### What did you expect to happen?
The extension to update to the latest version.

### Anything else we should know?
Verified on FF62.0a1 under Wind 7 64-bit in AMO-dev and stage servers. 
This issue is not reproducing on AMO prod.

**Comment by EnTeQuAk** [comment]
```
Traceback (most recent call last):
File "./services/wsgi/versioncheck.py", line 13, in <module>
from update import application  # noqa
File "/data/olympia/services/update.py", line 22, in <module>
from .utils import get_cdn_url, log_configure, PLATFORM_NAMES_TO_CONSTANTS
ValueError: Attempted relative import in non-package
```

This is very likely related to https://github.com/mozilla/addons-server/pull/8372

**Comment by diox** [comment]
@cosminbadescuSV let me know if that fixes it for you on dev and I'll cherry-pick this to stage.

**Comment by cosminbadescuSV** [comment]
This issue is verified as fixed on AMO-dev in FF62 under Win 7 64-bit.

![animation](https://user-images.githubusercontent.com/15885467/41038348-80a58864-699e-11e8-8ef1-2944cae4c9e2.gif)
