### ISSUE TITLE
Recent travis build failures (log them here, let's report them)

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8555]
An ongoing log of (random) errors that happen during our Travis runs. Let's save them here so that we're able to report them easier.

**Comment by EnTeQuAk** [comment]
https://travis-ci.org/mozilla/addons-server/jobs/393558829 (will be restarted though)

```
11.19s$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install swig oracle-java8-set-default elasticsearch gettext librsvg2-bin pngcrush
Reading package lists...
Building dependency tree...
Reading state information...
gettext is already the newest version (0.18.3.1-1ubuntu3).
Suggested packages:
  swig-doc swig-examples swig2.0-examples swig2.0-doc
The following packages will be REMOVED:
  oracle-java9-set-default
The following NEW packages will be installed:
  librsvg2-bin oracle-java8-set-default pngcrush swig swig2.0
The following packages will be upgraded:
  elasticsearch
1 upgraded, 5 newly installed, 1 to remove and 196 not upgraded.
Need to get 34.6 MB of archives.
After this operation, 5,144 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu trusty/main amd64 librsvg2-bin amd64 2.40.2-1 [15.6 kB]
Get:2 http://archive.ubuntu.com/ubuntu trusty/universe amd64 pngcrush amd64 1.7.65-0.1 [52.6 kB]
Get:3 http://archive.ubuntu.com/ubuntu trusty/main amd64 swig2.0 amd64 2.0.11-1ubuntu2 [875 kB]
Get:4 http://archive.ubuntu.com/ubuntu trusty/main amd64 swig amd64 2.0.11-1ubuntu2 [6,272 B]
Get:5 https://artifacts.elastic.co/packages/5.x/apt stable/main amd64 elasticsearch all 5.6.10 [33.7 MB]
Err:6 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main i386 oracle-java8-set-default all 8u151-1~webupd8~0
  404  Not Found
Err:6 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main i386 oracle-java8-set-default all 8u151-1~webupd8~0
  404  Not Found
Fetched 949 kB in 7s (127 kB/s)
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/pool/main/o/oracle-java8-installer/oracle-java8-set-default_8u151-1~webupd8~0_all.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
apt-get.diagnostics
apt-get install failed
$ cat ~/apt-get-update.log
Ign:1 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 InRelease
Get:2 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release [2,495 B]
Get:3 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release.gpg [801 B]
Get:4 https://dl.hhvm.com/ubuntu trusty InRelease
Get:5 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty InRelease [15.4 kB]
Get:6 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4/multiverse amd64 Packages [11.2 kB]
Get:7 http://security.ubuntu.com/ubuntu trusty-security InRelease [65.9 kB]
Get:9 https://dl.hhvm.com/ubuntu trusty/main amd64 Packages [1,802 B]
Get:10 http://security.ubuntu.com/ubuntu trusty-security/universe Sources [88.9 kB]
Get:11 http://apt.postgresql.org/pub/repos/apt trusty-pgdg InRelease [56.5 kB]
Get:13 http://security.ubuntu.com/ubuntu trusty-security/main amd64 Packages [924 kB]
Get:8 http://dl.bintray.com/apache/cassandra 39x InRelease [3,168 B]
Get:14 http://apt.postgresql.org/pub/repos/apt trusty-pgdg/main amd64 Packages [165 kB]
Ign:15 http://dl.google.com/linux/chrome/deb stable InRelease
Get:16 http://dl.google.com/linux/chrome/deb stable Release [1,189 B]
Get:17 http://security.ubuntu.com/ubuntu trusty-security/main i386 Packages [852 kB]
Get:18 http://dl.google.com/linux/chrome/deb stable Release.gpg [819 B]
Get:19 http://apt.postgresql.org/pub/repos/apt trusty-pgdg/main i386 Packages [163 kB]
Get:20 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1,107 B]
Get:21 https://artifacts.elastic.co/packages/5.x/apt stable InRelease
Ign:21 https://artifacts.elastic.co/packages/5.x/apt stable InRelease
Get:23 https://artifacts.elastic.co/packages/5.x/apt stable Release.gpg
Get:24 http://security.ubuntu.com/ubuntu trusty-security/restricted amd64 Packages [18.1 kB]
Get:25 http://security.ubuntu.com/ubuntu trusty-security/restricted i386 Packages [17.8 kB]
Get:26 http://security.ubuntu.com/ubuntu trusty-security/universe amd64 Packages [292 kB]
Get:27 http://security.ubuntu.com/ubuntu trusty-security/universe i386 Packages [280 kB]
Get:28 http://security.ubuntu.com/ubuntu trusty-security/multiverse amd64 Packages [4,718 B]
Get:29 http://security.ubuntu.com/ubuntu trusty-security/multiverse i386 Packages [4,877 B]
Ign:12 http://toolbelt.heroku.com/ubuntu ./ InRelease
Hit:30 http://toolbelt.heroku.com/ubuntu ./ Release
Ign:32 https://packagecloud.io/computology/apt-backport/ubuntu trusty InRelease
Get:33 https://artifacts.elastic.co/packages/5.x/apt stable/main amd64 Packages [38.3 kB]
Get:34 https://artifacts.elastic.co/packages/5.x/apt stable/main i386 Packages [38.3 kB]
Err:35 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty InRelease
  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
Err:36 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty InRelease
  Unable to connect to ppa.launchpad.net:http:
Err:37 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty InRelease
  Unable to connect to ppa.launchpad.net:http:
Err:38 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty InRelease
  Unable to connect to ppa.launchpad.net:http:
Err:39 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease
  Unable to connect to ppa.launchpad.net:http:
Ign:40 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main amd64 Packages
Ign:41 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main i386 Packages
Ign:40 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main amd64 Packages
Ign:41 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main i386 Packages
Ign:40 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main amd64 Packages
Ign:41 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main i386 Packages
Err:40 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main amd64 Packages
  Unable to connect to ppa.launchpad.net:http:
Err:41 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main i386 Packages
  Unable to connect to ppa.launchpad.net:http:
Ign:42 https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease
Ign:43 http://archive.ubuntu.com/ubuntu trusty InRelease
Get:44 http://archive.ubuntu.com/ubuntu trusty-updates InRelease [65.9 kB]
Get:46 http://archive.ubuntu.com/ubuntu trusty-backports InRelease [65.9 kB]
Hit:47 http://archive.ubuntu.com/ubuntu trusty Release
Get:49 http://archive.ubuntu.com/ubuntu trusty-updates/universe Sources [253 kB]
Get:51 http://archive.ubuntu.com/ubuntu trusty-updates/main amd64 Packages [1,348 kB]
Get:52 http://archive.ubuntu.com/ubuntu trusty-updates/main i386 Packages [1,274 kB]
Get:55 http://archive.ubuntu.com/ubuntu trusty-updates/restricted amd64 Packages [21.4 kB]
Get:56 http://archive.ubuntu.com/ubuntu trusty-updates/restricted i386 Packages [21.1 kB]
Get:57 http://archive.ubuntu.com/ubuntu trusty-updates/universe amd64 Packages [587 kB]
Get:59 http://archive.ubuntu.com/ubuntu trusty-updates/universe i386 Packages [577 kB]
Get:60 http://archive.ubuntu.com/ubuntu trusty-updates/multiverse amd64 Packages [16.0 kB]
Get:62 http://archive.ubuntu.com/ubuntu trusty-updates/multiverse i386 Packages [16.5 kB]
Get:63 http://archive.ubuntu.com/ubuntu trusty-backports/universe amd64 Packages [52.5 kB]
Get:64 http://archive.ubuntu.com/ubuntu trusty-backports/universe i386 Packages [52.4 kB]
Fetched 7,318 kB in 18s (400 kB/s)
Reading package lists...
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
```


https://github.com/mozilla/addons-server/pull/8551
```$ export GOPATH=$HOME/go
before_install.3
0.01s$ export PATH=$HOME/usr/local/go/bin:$GOPATH/bin:$PATH
install.1
0.04s$ nvm current
v8.9.1
install.2
0.02s$ nvm deactivate
/home/travis/.nvm/*/bin removed from $PATH
/home/travis/.nvm/*/share/man removed from $MANPATH
7.92s$ nvm install 6
curl: (35) Unknown SSL protocol error in connection to nodejs.org:443 
Version '6' not found - try `nvm ls-remote` to browse available versions.
The command "nvm install 6" failed and exited with 3 during .
```

**Comment by eviljeff** [comment]
https://travis-ci.org/eviljeff/olympia/jobs/393225499 (not 100% sure if Travis fail or us but can't replicate locally)
Will restart so copying to pastebin: https://pastebin.com/XppwEE8i

**Comment by diox** [comment]
Also seen that 
```
E: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/pool/main/o/oracle-java8-installer/oracle-java8-set-default_8u151-1~webupd8~0_all.deb  404  Not Found
```

A few times. Which is weird. Could it be an issue on launchpad side?

**Comment by eviljeff** [comment]
Got the following in https://travis-ci.org/mozilla/addons-server/jobs/394103429
```
Installing collected packages: Pygments, Sphinx, alabaster, docutils, imagesize, sphinxcontrib-httpdomain, sphinx-rtd-theme, typing, sphinxcontrib-websupport, snowballstemmer
Successfully installed Pygments-2.2.0 Sphinx-1.7.5 alabaster-0.7.11 docutils-0.14 imagesize-1.0.0 snowballstemmer-1.2.1 sphinx-rtd-theme-0.4.0 sphinxcontrib-httpdomain-1.6.1 sphinxcontrib-websupport-1.1.0 typing-3.6.4
pip install --progress-bar=off --no-deps --exists-action=w -r requirements/prod_without_hash.txt
Obtaining django-cache-machine from git+https://github.com/EnTeQuAk/django-cache-machine@1cac98a3e1dcc3cb654665cc67b6b15ab60d62c4#egg=django-cache-machine (from -r requirements/prod_without_hash.txt (line 2))
  Cloning https://github.com/EnTeQuAk/django-cache-machine (to revision 1cac98a3e1dcc3cb654665cc67b6b15ab60d62c4) to ./.tox/es/src/django-cache-machine
fatal: unable to access 'https://github.com/EnTeQuAk/django-cache-machine/': gnutls_handshake() failed: A TLS packet with unexpected length was received.
Command "git clone -q https://github.com/EnTeQuAk/django-cache-machine /home/travis/build/mozilla/addons-server/.tox/es/src/django-cache-machine" failed with error code 128 in None
make: *** [install_python_dependencies] Error 1
ERROR: InvocationError: '/usr/bin/make -f Makefile-docker update_deps'
```
(going to restart the job)

**Comment by eviljeff** [comment]
In https://travis-ci.org/eviljeff/olympia/jobs/394562181
```
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install swig elasticsearch gettext librsvg2-bin pngcrush
Reading package lists...
Building dependency tree...
Reading state information...
Package librsvg2-bin is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
Package pngcrush is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Unable to locate package swig
E: Package 'librsvg2-bin' has no installation candidate
E: Package 'pngcrush' has no installation candidate
apt-get.diagnostics
apt-get install failed
$ cat ~/apt-get-update.log
Get:1 http://apt.postgresql.org/pub/repos/apt trusty-pgdg InRelease [56.5 kB]
Ign:3 http://dl.google.com/linux/chrome/deb stable InRelease
Ign:4 http://toolbelt.heroku.com/ubuntu ./ InRelease
Get:5 http://dl.google.com/linux/chrome/deb stable Release [1,189 B]
Get:7 http://dl.google.com/linux/chrome/deb stable Release.gpg [819 B]
Hit:6 http://toolbelt.heroku.com/ubuntu ./ Release
Get:8 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1,106 B]
Get:9 http://apt.postgresql.org/pub/repos/apt trusty-pgdg/main amd64 Packages [165 kB]
Get:11 http://apt.postgresql.org/pub/repos/apt trusty-pgdg/main i386 Packages [163 kB]
Hit:12 https://packagecloud.io/computology/apt-backport/ubuntu trusty InRelease
Get:2 http://dl.bintray.com/apache/cassandra 39x InRelease [3,168 B]
Get:19 https://artifacts.elastic.co/packages/5.x/apt stable InRelease
Ign:19 https://artifacts.elastic.co/packages/5.x/apt stable InRelease
Get:21 https://artifacts.elastic.co/packages/5.x/apt stable Release.gpg
Get:22 https://artifacts.elastic.co/packages/5.x/apt stable/main amd64 Packages [38.3 kB]
Get:23 https://artifacts.elastic.co/packages/5.x/apt stable/main i386 Packages [38.3 kB]
Get:24 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty InRelease [15.4 kB]
Ign:25 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty InRelease
Get:26 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty InRelease [15.4 kB]
Get:27 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty InRelease [15.4 kB]
Get:28 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty InRelease [15.4 kB]
Get:29 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease [15.5 kB]
Get:30 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main amd64 Packages [1,706 B]
Get:31 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main i386 Packages [1,708 B]
Get:32 https://dl.hhvm.com/ubuntu trusty InRelease
Get:33 https://dl.hhvm.com/ubuntu trusty/main amd64 Packages [1,798 B]
Err:34 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 InRelease
  Could not connect to repo.mongodb.org:80 (13.33.87.220), connection timed out
Hit:35 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release
Err:37 http://mirror.jmu.edu/pub/ubuntu trusty InRelease
  Could not connect to mirror.jmu.edu:80 (134.126.36.183), connection timed out
Err:38 http://mirror.jmu.edu/pub/ubuntu trusty-updates InRelease
  Unable to connect to mirror.jmu.edu:http:
Err:39 http://mirror.jmu.edu/pub/ubuntu trusty-backports InRelease
  Unable to connect to mirror.jmu.edu:http:
Err:40 http://mirror.jmu.edu/pub/ubuntu trusty-security InRelease
  Unable to connect to mirror.jmu.edu:http:
Get:41 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main amd64 Packages [3,472 B]
Get:42 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main i386 Packages [3,472 B]
Get:43 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main amd64 Packages [4,880 B]
Get:44 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main i386 Packages [4,884 B]
Get:45 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main amd64 Packages [430 B]
Ign:46 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main i386 Packages
Ign:47 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main amd64 Packages
Ign:48 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main i386 Packages
Ign:46 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main i386 Packages
Ign:47 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main amd64 Packages
Ign:48 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main i386 Packages
Ign:46 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main i386 Packages
Ign:47 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main amd64 Packages
Ign:48 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main i386 Packages
Err:46 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main i386 Packages
  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
Err:47 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main amd64 Packages
  Unable to connect to ppa.launchpad.net:http:
Err:48 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main i386 Packages
  Unable to connect to ppa.launchpad.net:http:
Fetched 488 kB in 40s (12.2 kB/s)
Reading package lists...
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
W: Failed to fetch http://mirror.jmu.edu/pub/ubuntu/dists/trusty/InRelease  Could not connect to mirror.jmu.edu:80 (134.126.36.183), connection timed out
W: Failed to fetch http://mirror.jmu.edu/pub/ubuntu/dists/trusty-updates/InRelease  Unable to connect to mirror.jmu.edu:http:
W: Failed to fetch http://mirror.jmu.edu/pub/ubuntu/dists/trusty-backports/InRelease  Unable to connect to mirror.jmu.edu:http:
W: Failed to fetch http://mirror.jmu.edu/pub/ubuntu/dists/trusty-security/InRelease  Unable to connect to mirror.jmu.edu:http:
W: Failed to fetch http://repo.mongodb.org/apt/ubuntu/dists/trusty/mongodb-org/3.4/InRelease  Could not connect to repo.mongodb.org:80 (13.33.87.220), connection timed out
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/main/binary-i386/Packages  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install swig elasticsearch gettext librsvg2-bin pngcrush" failed and exited with 100 during .
```
(will restart)

**Comment by eviljeff** [comment]
And from https://travis-ci.org/eviljeff/olympia/jobs/394562182
```
$ pip install --upgrade pip wheel setuptools tox==2.9.1
Collecting pip
  Downloading https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl (1.3MB)
Exception:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 324, in read
    flush_decoder = True
  File "/opt/python/2.7.14/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 246, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
The command "pip install --upgrade pip wheel setuptools tox==2.9.1" failed and exited with 2 during .
```

**Comment by EnTeQuAk** [comment]
Closing since these seem to be fixed.
