### ISSUE TITLE
Fix recent circleci failures

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8593]
We are seeing regular circleci failures

```python
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 100, in loaddata
    self.load_label(fixture_label)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 157, in load_label
    obj.save(using=self.using)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/django/core/serializers/base.py", line 173, in save
    models.Model.save_base(self.object, using=using, raw=True)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/code/.tox/ui-tests/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
django.db.utils.OperationalError: Problem installing fixture '/code/src/olympia/versions/fixtures/initial.json': Could not load translations.Translation(pk=2): (1366, "Incorrect string value: '\\xCE\\xAD\\xCE\\xBA\\xCE\\xB4...' for column 'localized_string' at row 1")
```

something introduced them to happen regularly.

**Comment by EnTeQuAk** [comment]
This broke, as I feared in e482894b025fc80f7e72a674260e92c8221d1cca

**Comment by EnTeQuAk** [comment]
https://github.com/django-extensions/django-extensions/commit/0791541788798247971a652c55a955304bd68d6d is the commit that introduced our breakage.

This is a bit confusing since I'd guess that utf-8 support is something we want? 

We are also setting

```python
DATABASES['default']['TEST_CHARSET'] = 'utf8'
DATABASES['default']['TEST_COLLATION'] = 'utf8_general_ci'
```

… Still investigating.

**Comment by EnTeQuAk** [comment]
Indeed… by default docker-setup database get's created with `latin1`

```
+--------------------+----------------------------+
| schema_name        | default_character_set_name |
+--------------------+----------------------------+
| information_schema | utf8                       |
| mysql              | latin1                     |
| olympia            | latin1                     |
| performance_schema | utf8                       |
| sys                | utf8                       |
| test_olympia       | utf8                       |
| test_olympia_gw4   | utf8                       |
| test_olympia_gw5   | utf8                       |
+--------------------+----------------------------+
```

so…

```bash
root@c70bc1c0470c:/code# python manage.py reset_db --no-utf8
{"EnvVersion": "2.0", "Type": "z.startup", "Severity": 6, "Fields": {"msg": "Set RECURSION_LIMIT to 10000", "remoteAddressChain": "", "uid": ""}, "Timestamp": 1529565428161613056, "Logger": "http_app_addons", "Hostname": "c70bc1c0470c", "Pid": 5372}
{"EnvVersion": "2.0", "Type": "raven.contrib.django.client.DjangoClient", "Severity": 7, "Fields": {"msg": "Configuring Raven for host: None", "remoteAddressChain": "", "uid": ""}, "Timestamp": 1529565428167828992, "Logger": "http_app_addons", "Hostname": "c70bc1c0470c", "Pid": 5372}
{"EnvVersion": "2.0", "Type": "raven.contrib.django.client.DjangoClient", "Severity": 6, "Fields": {"msg": "Raven is not configured (logging is disabled). Please see the documentation for more information.", "remoteAddressChain": "", "uid": ""}, "Timestamp": 1529565428168915968, "Logger": "http_app_addons", "Hostname": "c70bc1c0470c", "Pid": 5372}
{"EnvVersion": "2.0", "Type": "raven.base.Client", "Severity": 7, "Fields": {"msg": "Configuring Raven for host: None", "remoteAddressChain": "", "uid": ""}, "Timestamp": 1529565428281198080, "Logger": "http_app_addons", "Hostname": "c70bc1c0470c", "Pid": 5372}
{"EnvVersion": "2.0", "Type": "raven.base.Client", "Severity": 6, "Fields": {"msg": "Raven is not configured (logging is disabled). Please see the documentation for more information.", "remoteAddressChain": "", "uid": ""}, "Timestamp": 1529565428282301952, "Logger": "http_app_addons", "Hostname": "c70bc1c0470c", "Pid": 5372}

You have requested a database reset.
This will IRREVERSIBLY DESTROY
ALL data in the database "olympia".
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
{"EnvVersion": "2.0", "Type": "root", "Severity": 6, "Fields": {"msg": "Executing... \"DROP DATABASE IF EXISTS `olympia`\"", "remoteAddressChain": "", "uid": ""}, "Timestamp": 1529565429404851968, "Logger": "http_app_addons", "Hostname": "c70bc1c0470c", "Pid": 5372}
{"EnvVersion": "2.0", "Type": "root", "Severity": 6, "Fields": {"msg": "Executing... \"CREATE DATABASE `olympia` CHARACTER SET utf8\"", "remoteAddressChain": "", "uid": ""}, "Timestamp": 1529565429406272768, "Logger": "http_app_addons", "Hostname": "c70bc1c0470c", "Pid": 5372}
Reset successful.


root@c70bc1c0470c:/code# python manage.py reset_db


{"EnvVersion": "2.0", "Type": "z.startup", "Severity": 6, "Fields": {"msg": "Set RECURSION_LIMIT to 10000", "remoteAddressChain": "", "uid": ""}, "Timestamp": 1529565444685710080, "Logger": "http_app_addons", "Hostname": "c70bc1c0470c", "Pid": 5379}
{"EnvVersion": "2.0", "Type": "raven.contrib.django.client.DjangoClient", "Severity": 7, "Fields": {"msg": "Configuring Raven for host: None", "remoteAddressChain": "", "uid": ""}, "Timestamp": 1529565444692423936, "Logger": "http_app_addons", "Hostname": "c70bc1c0470c", "Pid": 5379}
{"EnvVersion": "2.0", "Type": "raven.contrib.django.client.DjangoClient", "Severity": 6, "Fields": {"msg": "Raven is not configured (logging is disabled). Please see the documentation for more information.", "remoteAddressChain": "", "uid": ""}, "Timestamp": 1529565444693510144, "Logger": "http_app_addons", "Hostname": "c70bc1c0470c", "Pid": 5379}
{"EnvVersion": "2.0", "Type": "raven.base.Client", "Severity": 7, "Fields": {"msg": "Configuring Raven for host: None", "remoteAddressChain": "", "uid": ""}, "Timestamp": 1529565444809029120, "Logger": "http_app_addons", "Hostname": "c70bc1c0470c", "Pid": 5379}
{"EnvVersion": "2.0", "Type": "raven.base.Client", "Severity": 6, "Fields": {"msg": "Raven is not configured (logging is disabled). Please see the documentation for more information.", "remoteAddressChain": "", "uid": ""}, "Timestamp": 1529565444810211840, "Logger": "http_app_addons", "Hostname": "c70bc1c0470c", "Pid": 5379}

You have requested a database reset.
This will IRREVERSIBLY DESTROY
ALL data in the database "olympia".
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
{"EnvVersion": "2.0", "Type": "root", "Severity": 6, "Fields": {"msg": "Executing... \"DROP DATABASE IF EXISTS `olympia`\"", "remoteAddressChain": "", "uid": ""}, "Timestamp": 1529565446005004800, "Logger": "http_app_addons", "Hostname": "c70bc1c0470c", "Pid": 5379}
{"EnvVersion": "2.0", "Type": "root", "Severity": 6, "Fields": {"msg": "Executing... \"CREATE DATABASE `olympia` \"", "remoteAddressChain": "", "uid": ""}, "Timestamp": 1529565446005971968, "Logger": "http_app_addons", "Hostname": "c70bc1c0470c", "Pid": 5379}
Reset successful.
```

looks kinda broken to me…

**Comment by EnTeQuAk** [comment]
https://github.com/django-extensions/django-extensions/pull/1214

**Comment by AlexandraMoga** [comment]
Please add STR or the label 'qa:not needed'
Thanks
