### ISSUE TITLE
L10n extraction broken by django template

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#8716]
`manage.py extract` fails on master:
```
(...)
Extracting all strings in domain django...
(...)
  src/olympia/users/templates/admin/users/userprofile/change_form.html
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/puente/management/commands/extract.py", line 39, in handle
    msgid_bugs_address=get_setting('MSGID_BUGS_ADDRESS'),
  File "/usr/local/lib/python2.7/site-packages/puente/commands.py", line 122, in extract_command
    for filename, lineno, msg, cmts, ctxt in extracted:
  File "/usr/local/lib/python2.7/site-packages/babel/messages/extract.py", line 157, in extract_from_dir
    dirpath=absname,
  File "/usr/local/lib/python2.7/site-packages/babel/messages/extract.py", line 212, in check_and_call_extract_file
    strip_comment_tags=strip_comment_tags
  File "/usr/local/lib/python2.7/site-packages/babel/messages/extract.py", line 241, in extract_from_file
    strip_comment_tags))
  File "/usr/local/lib/python2.7/site-packages/babel/messages/extract.py", line 322, in extract
    for lineno, funcname, messages, comments in results:
  File "/usr/local/lib/python2.7/site-packages/jinja2/ext.py", line 609, in babel_extract
    node = environment.parse(source)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 493, in parse
    self.handle_exception(exc_info, source_hint=source)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<unknown>", line 2, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'load'.
```

**Comment by vcarciu** [comment]
Can you please add some STRs to this bug or mark it as "qa: not needed" ?
