### ISSUE TITLE
New xpi download links return 404

### ISSUE THREAD

**Issue by berzniz** [mozilla/addons-server#8995]
### Describe the problem and steps to reproduce it:
I've signed a file on AMO using API for self deployment, but the download link leads to a 404 page (served by Nginx on IP 54.71.77.164) instead of being downloadable.
Old versions are downloadable.

Console output:
```
Error: Got a 404 response when downloading https://addons.mozilla.org/api/v3/file/1026043/REDUCTED.xpi?src=api
    at Request.<anonymous> (~/node_modules/sign-addon/dist/webpack:/src/amo-client.js:293:21)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (~/node_modules/request/request.js:986:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
```

### What happened?
I signed an extension using the API, it was a success but the link provided by the response leads to a 404 NOT FOUND page.

### What did you expect to happen?
I expected to have a downloadable file at the link provided by the signing success response

### Anything else we should know?
Link to portal: https://addons.mozilla.org/en-US/developers/addon/toriihq/versions
API: Using `sign-addon` version 0.3.0 from nodejs
This is the error:
![image](https://user-images.githubusercontent.com/170214/43255051-754c50a6-90d1-11e8-942d-dea833f81eda.png)

**Comment by diox** [comment]
Hi,

Sorry about this. I suspect this is a duplicate of https://github.com/mozilla/addons/issues/324

**Comment by berzniz** [comment]
Thanks! I can confirm that switching the AMO to `visible` made the file downloadable again
